### ISSUE TITLE
Deploy binary dependencies with the gajim plugin

### ISSUE THREAD

**Issue by kalkin** [kalkin/gajim-omemo#10]
Bundle the `x64` axolotl library with the plugin

**Comment by lovetox** [comment]
on Windows axolotl is already bundled.

on Linux the best way in my opinion would be to create packages for the various distributions

The Plugin is right now in:
Debian-Unstable
AUR for Arch

someone told me if something is in Debian-Unstable it will end up in Ubuntu someday.

so what distributions are missing and should be supported?

Fedora?

**Comment by philfry** [comment]
For Fedora I wrote these spec files. Build and install `python-axolotl-curve25519` before building `python-axolotl`.

[python-axolotl.spec](https://github.com/omemo/gajim-omemo/files/606911/python-axolotl.spec.txt)
[python-axolotl-curve25519.spec](https://github.com/omemo/gajim-omemo/files/606912/python-axolotl-curve25519.spec.txt)

See also:
https://reposerv.unixadm.org/fedora/24/x86_64/repoview/python-axolotl.html
https://reposerv.unixadm.org/fedora/24/x86_64/repoview/python-axolotl-curve25519.html

Have phun

**Comment by lovetox** [comment]
@philfry thanks.

the links say License: BSD

but python-axolotl is under GPL, im no expert on the topic but i think its not possible to make it BSD

**Comment by philfry** [comment]
Sorry. It's fixed now.

[python-axolotl.spec](https://github.com/omemo/gajim-omemo/files/617146/python-axolotl.spec.txt)
[python-axolotl-curve25519.spec](https://github.com/omemo/gajim-omemo/files/617145/python-axolotl-curve25519.spec.txt)

**Comment by lovetox** [comment]
Could you tell me how a user on fedora would install those packages?

so i can add it to the readme please
thanks

**Comment by philfry** [comment]
Sure:

1. add this snippet to `/etc/yum.repos.d/ux.repo`
```
[ux]
name=Unixadm.org - Fedora $releasever base repository
baseurl=http://reposerv.unixadm.org/fedora/$releasever/$basearch/
enabled=1
includepkgs=python-axolotl python-axolotl-curve25519
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-UNIXADM
gpgcheck=1
```
2. (optional) fetch my [gpg key](https://www.unixadm.org/RPM-GPG-KEY-UNIXADM.asc) and save it to `/etc/pki/rpm-gpg/RPM-GPG-KEY-UNIXADM` (or else, set gpgcheck to 0)

3. `dnf install python-axolotl`
