### ISSUE TITLE
can't activate OMEMO plugin

### ISSUE THREAD

**Issue by eternalbit** [kalkin/gajim-omemo#105]
I can see the OMEMO plugin in the plugin manager, but cannot activate it.
_python-axolotl_ is installed.

I ran:
`gajim -l gajim.plugin_system.omemo=DEBUG` as suggested [here](https://github.com/omemo/gajim-omemo/wiki/It-doesnt-work,-what-should-i-do%3F-%28Linux%29)

This gave me:
`(E) gajim.plugin_system.omemo No module named message`

What can I do?

Is this warning in the plugin manager inside the OMEMO plugin just a reminder to install _python-axolotl_ or does it indicate that some actual check for _python-axolotl_ failed?

> Warning: Please install python-axolotl.

Ok, now I read [#52](https://github.com/omemo/gajim-omemo/issues/52) ... which suggests that my version of _python-protobuf_ which is _2.5.0-9ubuntu1_ is too old :(

**Comment by lovetox** [comment]
Actually i think you are using an old outdated package from ubuntu, you should download version 1.35
over pip of python-axolotl

this has a dependency on protobuf 3, if it doesnt work, install protobuf 2.6.1

look at the wiki for linux here on github

**Comment by lovetox** [comment]
so is your issue solved?

**Comment by eternalbit** [comment]
I ran:
`su -c "pip install python-axolotl"`

... which gave me:
Requirement already satisfied (use --upgrade to upgrade): python-axolotl in /usr/local/lib/python2.7/dist-packages/python_axolotl-0.1.35-py2.7.egg

Requirement already satisfied (use --upgrade to upgrade): pycrypto in /usr/lib/python2.7/dist-packages (from python-axolotl)

Requirement already satisfied (use --upgrade to upgrade): python-axolotl-curve25519 in /usr/local/lib/python2.7/dist-packages/python_axolotl_curve25519-0.1-py2.7-linux-x86_64.egg (from python-axolotl)

Requirement already satisfied (use --upgrade to upgrade): protobuf>=3.0.0.b2 in /usr/local/lib/python2.7/dist-packages/protobuf-3.0.0-py2.7.egg (from python-axolotl)

Requirement already satisfied (use --upgrade to upgrade): six>=1.9 in /usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg (from protobuf>=3.0.0.b2->python-axolotl)

Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages/setuptools-25.2.0-py2.7.egg (from protobuf>=3.0.0.b2->python-axolotl)

Cleaning up...

I still get the same debug message for OMEMO.
So do I have to install protobuf 2.6.1 now?

**Comment by lovetox** [comment]
maybe you could try something for me

please run `pip install protobuf --upgrade` which should upgrade you to 3.0.0 not the beta version anymore. then try if the message is gone.

if it doesnt help downgrade with `pip install protobuf==2.6.1`

**Comment by eternalbit** [comment]
I ran:
`su -c "pip install protobuf --upgrade"`

... which gave me:
Requirement already up-to-date: protobuf in /usr/local/lib/python2.7/dist-packages/protobuf-3.0.0-py2.7.egg

Requirement already up-to-date: six>=1.9 in /usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg (from protobuf)

Requirement already up-to-date: setuptools in /usr/local/lib/python2.7/dist-packages/setuptools-25.2.0-py2.7.egg (from protobuf)

I still got the same debug message for OMEMO.

**Your last advice worked ... I ran:**
`su -c "pip install protobuf==2.6.1"`

**... now it works.**
Thanks a lot.
