### ISSUE TITLE
Messages sent from gajim to Conversations are not encrypted.

### ISSUE THREAD

**Issue by ghost** [kalkin/gajim-omemo#108]
When I send a OMEMO encrypted message from gajim to Conversations, Conversations warns in red that it's not encrypted. gajim does not warn about this and displays the message as if it was encrypted.

Messages sent between Conversations and Conversations do not have this issue.

gajim 0.16
gajim-omemo 0.8.1
Conversations 1.13.8

**Comment by lovetox** [comment]
please read the readme, you have to use the latest gajim version.
