### ISSUE TITLE
The OMEMO plugin may not get loaded with recent python-pkg-resources versions

### ISSUE THREAD

**Issue by ao2** [kalkin/gajim-omemo#113]
Hi, this report is informational, I suspect the problem is **not** actually in the OMEMO plugin but rather in demandimports, but I though you should know that the issue exists.
#### General information
- **Gajim Version:** 0.16.5
- **Plugin Version:** 0.8.1/0.9.0
- **OS:** Debian Unstable
#### Steps to reproduce
1. Install python-pkg-resources >= v25.3.0
2. launch gajim
#### Expected result

Gajim shoudl load normally and the OMEMO plugin should just work, instead with recent python-pkg-resources versions this does not happen, the plugin is not loaded and this message appears on the console:

```
31/08/2016 12:37:14 (E) gajim.plugin_system.omemo <unloaded module 'RLock'> object is not callable
31/08/2016 12:37:15 (E) gajim.plugin_system.omemo <unloaded module 'RLock'> object is not callable
```

For a more detailed analysis, and temporary workarounds see https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835472#15 and onwards.

Note that when using the plugin version 0.8.x this issue will prevent gajim from starting, but when using version 0.9.0 of the plugin gajim loads fine even when loading the OMEMO plugin fails, and this can leave connections unencrypted if the user overlooks the UI.

As I said I think the issue is with demandimport, I'll try contacting the gajim developers and/or the demandimport devs, but if anyone else has an opinion of what the best solution is, let me know.

Thanks,
   Antonio

**Comment by lovetox** [comment]
thanks for bringing this to our attention.

i will look into it, i think i can solve this without code changes to gajim

**Comment by lovetox** [comment]
so i will add this _tread to demand ignore list, hope that helps

**Comment by ao2** [comment]
Yes please, that's what the mercurial developers suggested.

If you have been following https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=835472 you can see that there is a chance that gajim will drop demandimport altogether in the future, so a temporary workaround in gajim-omemo is fine.

And keep an eye on the gajim release notes so that maybe you can remove demandimport too from the gajim-omemo code when gajim drops it.

Thanks,
   Antonio

**Comment by lovetox** [comment]
https://github.com/omemo/gajim-omemo/pull/114

included in the next version.
thanks
