### ISSUE TITLE
No module named legacymessageexception

### ISSUE THREAD

**Issue by BlauerHunger** [kalkin/gajim-omemo#115]
#### General information

Before opening an issue, please read our Wiki
- **Gajim Version:** 0.16.5-f5209cb10665 (package gajim-nightly from ftp.gajim.org/debian/)
- **Plugin Version:** 0.9.0
- **OS:** Debian Unstable
- **Server name:** jabber.ccc.de
#### Steps to reproduce
1. Start Gajim with OMEMO plugin installed (and python-axolotl)
2. Gajim logs "(E) gajim.plugin_system.omemo No module named legacymessageexception"
3. Try to enable OMEMO plugin -> doesn't work as checkbox is disabled
4. Plugin description shows "Warning: Error: No module named legacymessageexception"
#### Expected result

It should be possible to enable the plugin in the plugin manager. 
#### Additional information

I already tried this with the version of gajim in Debian Unstable, but there Gajim crashes with my setup when trying to start it. 

Which additional information/logfiles do you need?

**Comment by lovetox** [comment]
Are you sure you have all dependencys?

python-axolotl is needed

**Comment by BlauerHunger** [comment]
First I thought this wouldn't be a problem, but it turned out that I have to install the python-axolotl package from pip. **The one from Debian Unstable doesn't work.**
I think this information should be added to the README-file.

**Comment by lovetox** [comment]
it is in the Readme and also in the install wiki for Debian

**Comment by BlauerHunger** [comment]
There is no special note that the debian package python-axolotl doesn't work, and there it's still recommended to install it.

**Comment by lovetox** [comment]
it doesnt work for you, so make a bug report here or at debian

**Comment by BlauerHunger** [comment]
I think I'll do that, and sorry for the noise

**Comment by lovetox** [comment]
there is soon a new package in debian
`gajim-omemo`
https://ftp-master.debian.org/new.html
