### ISSUE TITLE
broken link on wiki page for windows

### ISSUE THREAD

**Issue by tristan-k** [kalkin/gajim-omemo#116]
The link to the windows setup.exe on the [wiki](https://github.com/omemo/gajim-omemo/wiki/Installing-on-Windows) is broken.

https://gajim.org/downloads/snap/win/gajim_0.16.5_axolotl.exe

**Comment by lovetox** [comment]
yeah a new gajim version is inbound

**Comment by lovetox** [comment]
should be fixed
