### ISSUE TITLE
Cannot send message to any contact

### ISSUE THREAD

**Issue by RalfJung** [kalkin/gajim-omemo#117]
#### General information

Before opening an issue, please read our Wiki
- **Gajim Version:** Current 0.16 branch
- **Plugin Version:** 0.9-6-ge619dd2
- **OS:** Debian testing
- **Server name:** self hosted
- **Server software:** prosody
#### Steps to reproduce
1. Try to send a message to any contact
#### Expected result

The message should be sent.
Instead, I get an error:

```
Traceback (most recent call last):
  File "/home/r/src/gajim/src/chat_control.py", line 797, in _on_message_textview_mykeypress_event
    self.send_message(message, xhtml=xhtml) # send the message
  File "/home/r/.local/share/gajim/plugins/omemo/ui.py", line 148, in omemo_send_message
    self.new_fingerprints_available()
  File "/home/r/.local/share/gajim/plugins/omemo/ui.py", line 194, in new_fingerprints_available
    fingerprints = self.state.store.getNewFingerprints(self.contact.jid)
  File "/home/r/.local/share/gajim/plugins/omemo/omemo/liteaxolotlstore.py", line 100, in getNewFingerprints
    return self.identityKeyStore.getNewFingerprints(jid)
  File "/home/r/.local/share/gajim/plugins/omemo/omemo/liteidentitykeystore.py", line 152, in getNewFingerprints
    for row in c.execute(q, (jid,)):
OperationalError: no such column: shown
```

I suspect some DB file around here is outdated... but the plugin should really take care of the necessary migrations itself, instead of making Gajim unusable.

**Comment by lovetox** [comment]
You have two options

either delete the DB, this would trigger new keys generated.
or you add the column yourself

see this issue for help:
https://github.com/omemo/gajim-omemo/issues/85

im sorry for the inconvenience, should not happen again.

**Comment by lovetox** [comment]
hm i dont know really why this happend

the migration is taken care by the plugin

this is the migration code

```
DROP TABLE signed_prekeys;
                CREATE TABLE IF NOT EXISTS signed_prekeys (
                    _id INTEGER PRIMARY KEY AUTOINCREMENT,
                    prekey_id INTEGER UNIQUE,
                    timestamp NUMERIC DEFAULT CURRENT_TIMESTAMP, record BLOB);
                ALTER TABLE identities ADD COLUMN shown INTEGER DEFAULT 0;
                UPDATE identities SET shown = 1;
```

maybe you can look what didnt go through here in your db

you also should set
`PRAGMA user_version=5`
when you are finished.

or you delete the db and start new, this would trigger a new key generated, your contact would have to trust a new fingerprint

**Comment by RalfJung** [comment]
I changed `user_version(self.dbConn) < 5` to `user_version(self.dbConn) <= 5`, restarted Gajim, changed it back, restarted Gajim again -- now things are working. Strange...
