### ISSUE TITLE
ability to disable omemo for different servers

### ISSUE THREAD

**Issue by Draic** [kalkin/gajim-omemo#119]
I am connectiong to multiple xmpp servers in gajim. One of them will for some reason disconnect me if omemo is enabled. This is most likely a problem with the servers config which is strange to begin with. But I would like to be able to disable omemo for specific servers so that it doesnt clash with them

**Comment by lovetox** [comment]
i have this feature already in a branch, because some other people also requested it.

i hope i can upload it in the next week

**Comment by functionpointer** [comment]
I would like this feature as well. I use gajim to connect to the chat of League of Legends, which works fine as long as OMEMO is not active. With OMEMO active i get disconnected as soon as OMEMO gets mentioned in the XML console.

**Comment by lovetox** [comment]
its already in HEAD, new version will hit the plugin repo of Gajim soon

**Comment by functionpointer** [comment]
Yes i just noticed the commits 9124577ff1ee07c81132d532c98052ec4db94099 and 9b2c989aa8ebd05bc857c95cad285afee9cb8e94 . After cloning the git repo and replacing the plugin folder i can confirm that it works correctly! Thank you!

**Comment by lovetox** [comment]
dont switch back to an older version, because the DB name was migrated to another name scheme, so if you go back to an older version the whole DB would be created new.

**Comment by functionpointer** [comment]
Oh interesting. I figured since the version number in the manifest.ini didnt change gajim wouldnt care much about the changed files and just run them. It's probably also going to notify me if there is a new version. Isn't it great that this is so easily possible? No compilation process, no checksums or certificates getting in the way. Just copy and go! Plus now i get to use git pull if i want a new version from git.

**Comment by lovetox** [comment]
this is possible now in version 0.9.5

Option is in the config Menu of the Plugin.
Please restart the client after moving accounts from and to the ignore list
