### ISSUE TITLE
(E) gajim.plugin_system.omemo No module named _message

### ISSUE THREAD

**Issue by 83bytes** [kalkin/gajim-omemo#120]
#### General information

I followed the instruction on ArchWiki to install the omemo plugin, but that did not work because of some error.
Then I followed the instructions on this page and finally managed to install the plugin in gajim
Hoever now it does not work and shows me this error: `Warning: Error: No module named _message`

Before opening an issue, please read our Wiki
- **Gajim Version:      0.16.5-2**
- **Plugin Version: 0.9** 
- **OS: Arch with i3wm** 
#### Debug output

[Logs](http://pastebin.com/NQiKp6hT) with `-l gajim.plugin-system.omemo=DEBUG`

**Comment by cippaciong** [comment]
> I followed the instruction on ArchWiki to install the omemo plugin, but that did not work because of some error.

What kind of error?

**Comment by 83bytes** [comment]
error: target not found: python2-axolotl-git
==> ERROR: 'pacman' failed to install missing dependencies.

**Comment by klemens** [comment]
You have to install [`python2-axolotl-git`](https://aur.archlinux.org/packages/python2-axolotl-git) (also from the AUR) first, which in turn depends on [`python2-axolotl-curve25519-git`](https://aur.archlinux.org/packages/python2-axolotl-curve25519-git/) from AUR.
You could also use an AUR helper which handles these dependencies automatically.

**Comment by lovetox** [comment]
@sohom154 did you get it to work?

**Comment by 83bytes** [comment]
yes!! It worked!

**Comment by gjedeer** [comment]
In my case upgrading gajim to the latest nightly helped fix this error
