### ISSUE TITLE
cannot activate OMEMO plugin on Ubuntu 16.10 final beta

### ISSUE THREAD

**Issue by fuelflo** [kalkin/gajim-omemo#122]
Hey, since I updated to Ubuntu 16.10 final beta I cannot activate the OMEMO plugin anymore.

Gajim Version: 0.16.5
OMEMO plugin version: 0.9.0
python-axolotl is already the newest version (0.1.7-1).
python-cryptography is already the newest version (1.5-2).

I get following error when trying to activate the plugin: 

> You need to install some dependencys, you can find install instructions for your system in the Github Wiki.
> 
> Warning: Error: Descriptors should not be created directly, but only retrieved from their parent. 

And thats the debug output:

> Logger gajim.plugin-system.omemo level set to 10
> 05.10.2016 17:36:11 (E) gajim.plugin_system.omemo Descriptors should not be created directly, but only retrieved from their parent.
> /home/flo/.local/share/gajim/plugins/gotr/ui.py:40: GtkWarning: Unknown property: GtkMenu.ubuntu-local
>   self.B.add_from_file(self.GTK_BUILDER_FILE_PATH)
> /usr/lib/python2.7/dist-packages/nbxmpp/tls_nb.py:436: DeprecationWarning: unicode for cipher_list is no longer accepted, use bytes
>   tcpsock._sslContext.set_cipher_list(self.cipher_list)

Anything I can do to fix it or you have to fix it in the code?

Thx in advance!

**Comment by lovetox** [comment]
2 of these errors are not from OMEMO

so you cant activate the plugin, i have to investigate what the error actually means.

**Comment by lovetox** [comment]
https://groups.google.com/forum/#!topic/linux.debian.bugs.dist/amfNKJWoOoE

you should probably downgrade to protobuf 2.6.1

**Comment by fuelflo** [comment]
Nope, the box is grey and I cannot activate it. I also already removed and reinstalled the plugin.

Am 5. Oktober 2016 19:24:02 MESZ, schrieb lovetox <notifications@github.com>:
>2 of these errors are not from OMEMO
>and the one that you have, i dont think it plays a role.
>
>lets start with what is not working?
>can you activate the plugin?

**Comment by lovetox** [comment]
so did it work?

**Comment by fuelflo** [comment]
sry, I was at a place with no internet for my pc.... ;)

indeed it worked when downgrading to protobuf 2.6.1.

**Comment by towo** [comment]
Just saying "downgrade" is not really the correct solution when people are running the distro-supplied version of protobuf.

**Comment by lovetox** [comment]
back in october that was the easiest solution,

since november ubuntu has a updated version of python-axolotl that should fix that problem.

**Comment by towo** [comment]
Totally doesn't. (16.10 here.)

What version of python-axolotl are you referring to? 0.1.7 is in the repositories.

**Comment by lovetox** [comment]
https://launchpad.net/ubuntu/+source/python-axolotl

0.1.35-1

**Comment by towo** [comment]
That one isn't in Ubuntu officially until April. ;)
