### ISSUE TITLE
Windows link doesn't work anymore

### ISSUE THREAD

**Issue by ronnicek** [kalkin/gajim-omemo#123]
#### General information

Before opening an issue, please read our Wiki
- **OS:** Windows 7
#### Steps to reproduce
1. Go to https://github.com/omemo/gajim-omemo/wiki/Installing-on-Windows
2. Click on link
#### Expected result

Download of file :)
#### Debug output

N/A

**Comment by lovetox** [comment]
Sorry, thats becasue Gajim 0.16.6 has everything onboard, no link necessary anymore :)
