### ISSUE TITLE
Delay when sending messages

### ISSUE THREAD

**Issue by mokasin** [kalkin/gajim-omemo#13]
On my system, when sending an OMEMO encrypted message to a Conversations client, there is a delay in the order of seconds.

Where does this bad performance come from? How to debug this?

**Comment by kalkin** [comment]
It's hard to say. It can be anything. It could be you mobile device which is slow doing encryption, it could be just a network/server delay.

**Comment by mokasin** [comment]
I observe this also, when sending messages between two accounts on the same server just using Gajim for both.

(Shortened)Debug log looks unsuspicious:

```
01/04/2016 15:18:07 (I) gajim.plugin_system.omemo binary
01/04/2016 15:18:07 (I) gajim.plugin_system.omemo Payload
01/04/2016 15:18:07 (I) gajim.plugin_system.omemo binary
01/04/2016 15:18:07 (D) gajim.plugin_system.omemo encrypted message
01/04/2016 15:18:07 (D) gajim.plugin_system.omemo {'keys': {1555228753: 'escaped characters', 236951316: 'escaped characters', 406261662: 'escaped characters', 33935950: 'escaped characters'}, 'jid': 'user@server.com', 'iv': 'escaped characters', 'payload': 'escaped characters', 'sid': 1901269236}
01/04/2016 15:18:07 (D) gajim.plugin_system.omemo Creating_msg{'keys': {1555228753: 'escaped characters', 236951316: 'escaped characters', 406261662: '3escaped characters', 33935950: 'escaped characters'}, 'jid': 'user@server.com', 'iv': 'escaped characters', 'payload': 'escaped characters', 'sid': 1901269236}
01/04/2016 15:18:07 (D) gajim.plugin_system.omemo server.com 1 → <message xmlns="jabber:client" to="user@server.com/Gajim" type="chat"><thread>string</thread><encrypted xmlns="eu.siacs.conversations.axolotl"><header sid="1901269236"><key rid="1555228753">string</key><key rid="236951316">string</key><key rid="406261662">string</key><key rid="33935950">string</key><iv>string</iv></header><payload>string</payload></encrypted></message>
01/04/2016 15:18:07 (D) gajim.plugin_system.omemo server.com ⇒ OMEMO msg received
01/04/2016 15:18:07 (D) gajim.plugin_system.omemo string
01/04/2016 15:18:07 (D) gajim.plugin_system.omemo string
01/04/2016 15:18:07 (D) gajim.plugin_system.omemo string
01/04/2016 15:18:07 (D) gajim.plugin_system.omemo string
01/04/2016 15:18:07 (D) gajim.plugin_system.omemo string
01/04/2016 15:18:07 (D) gajim.plugin_system.omemo string
01/04/2016 15:18:07 (D) gajim.plugin_system.omemo Parsed OMEMO message:{'keys': {1555228753: 'escaped characters', 236951316: 'escaped characters', 33935950: 'escaped characters', 406261662: 'escaped characters'}, 'iv': 'escaped characters', 'payload': 'escaped characters', 'sid': 1901269236}
01/04/2016 15:18:08 (D) gajim.plugin_system.omemo WhisperMessage -> binary
01/04/2016 15:18:08 (D) gajim.plugin_system.omemo Decrypted msg ⇒ test
01/04/2016 15:18:08 (D) gajim.plugin_system.omemo server.com → Missing device sessions: []
01/04/2016 15:18:08 (D) gajim.plugin_system.omemo server.com → Missing device sessions: []
```

**Comment by kalkin** [comment]
Please open Actions -> Advance -> Xml Console. Enable it and send any OMEMO encrypted message. The XML Console will show your message as soon as it hits the wire. If you have a lag between pressing enter and the message showing up in the XML Console, it's a Gajim or OMEMO issue. In any other case it should be network/server issue.

**Comment by mokasin** [comment]
I have a lag between pressing enter and the message showing up in the XML Console AND the message window. This delay does not happen, when I disable OMEMO.

**Comment by kalkin** [comment]
Interesting. So it's definitly crypto. Would be nice if you could debug it further. You could add some timestamp logging to `OmemoState.create_msg()` to figure out the hot spot.

**Comment by mokasin** [comment]
These are the timings I've got.

```
random data 0.00758099555969
device list = ... 0.000234127044678
for dev in devices_list 0.000190019607544
session_ciphers = self.session_ciphers[jid] 0.000137805938721
for dev in my_other_devices 0.927828073502
for rid, cipher in session_ciphers.items() 0.916749000549
aes_encrypt(key, iv, plaintext) 0.00656914710999
```

As you can see, the most time is spent dealing with the session keys of the other devices (there are no other devices online with the same jid in my case).

I'm not really sure, what the difference between
https://github.com/kalkin/gajim-omemo/blob/ffbaf3ae9d60c3747b92ca008c123c2256b88e16/state.py#L174
and
https://github.com/kalkin/gajim-omemo/blob/ffbaf3ae9d60c3747b92ca008c123c2256b88e16/state.py#L182
is.

**Comment by mokasin** [comment]
It seems

```
cipher.encrypt(key).serialize()
```

takes rather long on my system.

**Comment by kalkin** [comment]
Ok it's the encryption issue. The whole encryption happens [here in lines 182-188](https://github.com/kalkin/gajim-omemo/blob/ffbaf3ae9d60c3747b92ca008c123c2256b88e16/state.py#L182-L188). We encrypt the key for the cryptotext for each other device we have and for each device of our receiver. It takes time. If you want to follow further the in to the rabbit hole have a look at the [encrypt method](https://github.com/tgalal/python-axolotl/blob/9585d7212c95c47aa97e0a4d74b4a756e4d11daa/axolotl/sessioncipher.py#L29-L63) in `python-axolotl`. Perhaps we can optimize something?

**Comment by mokasin** [comment]
I've tried a bare metal version of the _encrypt()_ function by basically running this [code](https://github.com/tgalal/python-axolotl/blob/master/axolotl/tests/test_sessioncipher.py) using _initializeSessionsV3()_. There is virtually no delay on my system. But calling the _encrypt()_ function from the OMEMO plugin takes considerable more time (actually several orders of magnitude). This is weird. Something else must be going on.

Is the function called somehow differently?

**Comment by kalkin** [comment]
@mokasin Dunno how you tested it directly, but if you are using the OMEMO plugin your encryption is derived from previous encrypted messages. I imagine that this takes more work, than just plainly initialize a completely new session. Feel free to dig deeper.

**Comment by kalkin** [comment]
@mokasin I'm currently working on a standalone [omemo/python-omemo](/omemo/python-omemo) library. I'm working on adding tests which will make sure consistent behaviour. Care to add some tests which will measure the performance and guarantee that we do not get worse?

**Comment by kalkin** [comment]
I reproduced it on my notebook.

**Comment by lovetox** [comment]
native encryption is now implemented

the cryptography lib is needed for it to work

`pip install cryptography`
