### ISSUE TITLE
Plugin installed, but not visible in plugin list

### ISSUE THREAD

**Issue by COLABORATI** [kalkin/gajim-omemo#130]
**Gajim Version:** 0.16.6-81c36bd94098
- **Plugin Version:** dont know, just what is in the plugin list
- **OS:** eg Ubuntu 14.04
- **Server name:** jabber.ccc.de

Plugin is listed in the plugin installer. I select the plugin check box and click install button, looks like something is downloaded. However, the plugin does not show up in the 'installed plugins' area. 

Even worse: there is no message given why this happens, so user does not know anything about why this process failed. Please implement sane error handling and give a user message about what might be wrong. Thanks!

**Comment by lovetox** [comment]
please read the wiki
https://github.com/omemo/gajim-omemo/wiki/Installing-on-Linux

**Comment by lovetox** [comment]
we will have better error handling in the next version of the plugin
