### ISSUE TITLE
plugin fails to load on ubuntu 16.10

### ISSUE THREAD

**Issue by cromulentbanana** [kalkin/gajim-omemo#132]
#### General information

plugin fails to load with Warning: Error: Descriptors should not be created directly, but only retrieved from their parent. 

Before opening an issue, please read our Wiki
- **Gajim Version:** 0.16.5
- **Plugin Version:** 0.9.0
- **OS:** Ubuntu 16.10
#### Steps to reproduce
1. install gajim
2. sudo aptitude install python-axolotl
3. install the omemo plugin through the plugin installer
4. observe that the plugin can not be enabled and that an error is printed out in the logs: Error: Descriptors should not be created directly, but only retrieved from their parent. 
#### Expected result

What is the expected output? What do you see instead?
#### Debug output

Please start Gajim with `-l gajim.plugin-system.omemo=DEBUG` and post the log file
10/17/2016 18:34:56 (E) gajim.plugin_system.omemo Descriptors should not be created directly, but only retrieved from their parent.

**Comment by lovetox** [comment]
please downgrade to protobuf 2.6.1

**Comment by lovetox** [comment]
did that solve your problem?

**Comment by dennisguse** [comment]
Ubuntu 16.10
Omemo version 0.9.7
Gajim 0.16.5
Protobuf 3.0.0

Still not working.
Here is the requested output.

PS: Downgrading to protobuf 2.6.1 is not an option for me (too much manual maintenance effort. Sorry.).

dennis@noname:~$ gajim -l gajim.plugin-system.omemo=DEBUG

Logger gajim.plugin-system.omemo level set to 10
28.11.2016 11:16:40 (E) gajim.plugin_system.omemo Descriptors should not be created directly, but only retrieved from their parent.
/home/dennis/.local/share/gajim/plugins/gotr/ui.py:40: GtkWarning: Unknown property: GtkMenu.ubuntu-local
  self.B.add_from_file(self.GTK_BUILDER_FILE_PATH)
/usr/lib/python2.7/dist-packages/nbxmpp/tls_nb.py:436: DeprecationWarning: unicode for cipher_list is no longer accepted, use bytes
  tcpsock._sslContext.set_cipher_list(self.cipher_list)

**Comment by lovetox** [comment]
you have to install something manually, because with the packages ubuntu supplys its not going to work

either you downgrade protobuf or you install axolotl manually from here

https://launchpad.net/ubuntu/+source/python-axolotl/0.1.35-1

**Comment by dennisguse** [comment]
That would work, but I am not taking the risk ;)

PS: Would you mind keeping this issue open until it is fixed by Ubuntu 16.10.
This allows other people stumbling over the same issue to find it easier.

**Comment by alexandrestein** [comment]
- **Gajim Version**: 0.16.5
- **OMEMO Plugin Version**: 1.0.0
- **OS**: Ubuntu Gnome 16.10

This worked for me by simply downgrading **protobuf** with: **sudo pip install protobuf==2.6.1**
No manual operation needed.

And OMEMO woks great for me.

**Comment by lofidevops** [comment]
This worked for me:

* **Gajim version:** 0.16.5
* **OMEMO plugin version:** 1.0.3 (latest version, as downloaded by plugin installer)
* **OS:** Ubuntu Gnome 16.10

Downloaded and installed `python-axolotl_0.1.35-3_all.deb` from <https://packages.debian.org/stretch/all/python-axolotl/download>

(did not install protobuf)

**Comment by lovetox** [comment]
please use Gajim 0.16.7

**Comment by lovetox** [comment]
and provide a log file, when starting with `gajim -l gajim.plugin_system=DEBUG`

**Comment by maltris** [comment]
- **Gajim Version:** 0.16.7
- **OMEMO Plugin Version:** 1.0.3
- **OS:** Ubuntu 16.10

Did work after installing the older photobuf 2.6.1.

**Comment by lovetox** [comment]
you should not have to do this, please use the gajim-omemo debian package.

if it does not work report the bug to the debian bug tracker

**Comment by lofidevops** [comment]
@lovetox Thanks for the info. Are you saying that the correct versions of just `gajim.deb` `gajim-omemo.deb` and `python-axolotl.deb` should do the trick? (Assuming no packaging issues on Ubuntu.)

**Comment by lovetox** [comment]
ubuntu has only gajim 0.16.6 in theire repos

so i would add `deb ftp://ftp.gajim.org/debian unstable main` and install 0.16.7

afterwards you can install `gajim-omemo` from the ubuntu repos
https://launchpad.net/ubuntu/+source/gajim-omemo
it installs all dependencys necessary.

afterwards you can update omemo from inside gajims plugin-manager, actually you should get a popup to update 30 seconds after start.

**Comment by lovetox** [comment]
theoretically the gajim-omemo package should also work with 0.16.6, just for your information, but i would better use 0.16.7, not because of omemo, because of many bugfixes in gajim itself.

**Comment by kyu-sz** [comment]
Renaming any file creating descriptors to have suffix "_pb2.py" will solve this problem.

**Comment by lovetox** [comment]
the python_axolotl package should already have this fix included, because its long fixed in the debian repos.

its also fixed on git in python_axolotl

so from this point on i consider this a package error, as gajim cant do anything to fix that.
