### ISSUE TITLE
OMEMO not working in Group-Chat in Gajim

### ISSUE THREAD

**Issue by fanningert** [kalkin/gajim-omemo#137]
#### General information

Before opening an issue, please read our Wiki
- **Gajim Version:** 0.16.6
- **Plugin Version:** 0.9.5
- **OS:** ArchLinux
- **Server name:** self hosted
- **Server software:** prosody 0.10
- **Installed server modules:** many...
#### Steps to reproduce
1. I created a room for two JIDs of the same domain.
2. Open the room with the two JIDs
3. OMEMO ist disabled.
#### Expected result
- Message displayed on the top "‎OMEMO encryption disabled"
- OMEMO button is disabled
#### Debug output

```
2016-10-23 18:57:57 (W) gajim.plugin_system.omemo JID1@example.im => No devices for familie@xmpp-conference.example.im
```

I get the same message by JID2, when I connect to the room.

**Comment by lovetox** [comment]
Room has to be 
- Non-anonymous
- Contact has to be in your roster

if you change the room config instead of opening a new chat, gajim client has to rejoin the chat

**Comment by lovetox** [comment]
if you want to chat with people that use conversations client, you have to make the room `members-only` too

**Comment by fanningert** [comment]
I created the room fresh with following options. I also exit GAJIM and restart it.
- Make Room Persistent?            = true
- Make Room Moderated?           = true
- Make Publicly Searchable?      = true
- Make Room Members-Only?    = true

The members of the room are on my roster and I also trust there OMEMO key.

I tested in following scenarios.
1. JID1 and JID2 over GAJIM
   Result: FOR JID1 and JID2 the OMEMO is disabled
2. JID2 over Conversations, JID2 over GAJIM
   Result: FOR JID1 and JID2 the OMEMO is disabled

**Comment by lovetox** [comment]
Make Room Moderated? = true
Make Publicly Searchable? = true

it makes no sense to make a room publicly sarchable if no one can join because its member-only.
also i would not make it moderated as this i believe means, only a moderator can talk

you have to make the room non-anonymous, this means everyone can see the full jid

**Comment by lovetox** [comment]
if you struggle with this from gajim (many options) you can also create the room with conversations, it sets all options automatically

**Comment by fanningert** [comment]
Ok, I will test it.

It makes sense, for the members. Not every client auto connect to the room. And not every time the member knows the name of the room.

**Comment by fanningert** [comment]
Thanks, the only problem was the option `Who may discover real jids`. After I change the option from `moderators only` to `anyone` and reopen the room. Everything with omemo is working.

**Comment by dreamflasher** [comment]
It doesn't work for me. I created the room with conversations and within conversations it works -- but not with Gajim. When I send a message from my conversations client it only says in Gajim that this was an Omemo message and I need to install Omemo. (In 1:1 chats Omemo works nicely) I have set "Present real Jabber IDs to anyone"
