### ISSUE TITLE
Group Chat can't send message in an empty chat room

### ISSUE THREAD

**Issue by jocelynthode** [kalkin/gajim-omemo#138]
#### General information

* **Gajim Version:** 0.16.6
* **Plugin Version:** 0.9.6
* **OS:** Archlinux
* **Server name:** -
* **Server software:** -
* **Installed server modules:** MAM, etc.

#### Steps to reproduce

1. Create a non-anonymous chat room
2. Join it and be alone
3. Send a message
4. Window pops up telling you to trust a fingerprint but there are no fingerprints to trust

#### Expected result

Message should be sent to the room

**Comment by lovetox** [comment]
why should it be sent to room? there is no way someone can ever receive it.

**Comment by jocelynthode** [comment]
You are right my bad. It shouldn't be sent to the room. However an error message should be printed instead of displaying an empty fingerprint window IMHO.

Am 2. November 2016 20:10:54 MEZ, schrieb lovetox notifications@github.com:

> why should it be sent to room? there is no way someone can ever receive
> it.
> 
> ## 
> 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/omemo/gajim-omemo/issues/138#issuecomment-257968762

## 

Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by lovetox** [comment]
Moved https://dev.gajim.org/gajim/gajim-plugins/issues/267
