### ISSUE TITLE
http-upload + OMEMO file transfers can't be decrypted

### ISSUE THREAD

**Issue by ache** [kalkin/gajim-omemo#139]
#### General information
Instead of downloading and decrypting the given file by itself (via its added #... anchor) http-upload just put the link into the chat which can be downloaded by the browser of course when clicked, but since it is encrypted, there is nobody exists to decrypt it afterwards, so the browser downloads just garbage.
Please fix http-upload plugin to provide some integration with OMEMO and do some automation or add at least right-click option on the link in the chat which do the same.

* **Gajim Version:** 0.16.16-1
* **OS:** Windows 10
* **Server name:** jabber.ru
* **Server software:** ejabberd
* **Installed server modules:** MAM

**Comment by cippaciong** [comment]
http-upload is used only to upload some content and not to retrieve or display it.
You should look at https://trac-plugins.gajim.org/wiki/UrlImagePreviewPlugin

Or the two equivalent tools
https://github.com/iNPUTmice/ImageDownloader

https://git.ao2.it/conversations_http_downloader.git/

**Comment by ache** [comment]
I don't mean to display content at all, consider sending via http-upload some-file.zip

**Comment by cippaciong** [comment]
Check the last link then, it should handle a wider variety of file types.

**Comment by ache** [comment]
Your ImageDownloader URL perhaps is useful but not for Windows.
About  conversations_http_downloader.py, why not embed it into OMEMO/Gajim wih some sort of minimal GUI like right click I initially suggest?

**Comment by cippaciong** [comment]
I think both scripts can be easily adapted to run under windows as well. That said I agree on the fact that having this operation embedded in Gajim/OMEMO plugin would be a nice improvement for user experience.
I was just trying to provide you an instantly accessible solution/workaround :)

**Comment by lovetox** [comment]
@cippaciong both scripts are not easily adaptable

the java one just doesnt work on windows out of the box, you have to download each server certificate manually and add it manually via commandline to the java cert store.

python is not preinstalled on windows, gajim also doesnt depend on a installed version of python, it brings its own python version that only gajim can use, so to get such a script working on windows in an easy usable way it needs alot of knowhow.

but you are right its on the list for a long time, with files there are more considerations to make.

**Comment by lovetox** [comment]
We move with issues to Gitlab, this issue is already on Gitlab
https://dev.gajim.org/gajim/gajim-plugins/issues/154
