### ISSUE TITLE
Bad interaction with Gajim e2e encryption

### ISSUE THREAD

**Issue by RalfJung** [kalkin/gajim-omemo#14]
When chatting with someone else who also uses Gajim and OMEMO, we sometimes had the problem that Gajim started an e2e session so that messages sent from the PC ended up only on the peer's PC, but not on any of our phones. We fixed this now by disabling e2e sessions in the Gajim ACE, but maybe the plugin can do something about this. I can't remember having this problem with OTR, so maybe the OTR plugin found a way to properly disable e2e while it controls the session.

(Of course, interaction of OTR and OMEMO plugins running at the same time could also be interesting.)

**Comment by kalkin** [comment]
Thank you for your bug report. I can confirm there are issues when having e2e and OMEMO enabled side by side.

**Comment by kalkin** [comment]
As a work around you can disable E2E in the Preferences -> Advanced -> Advanced Configuration Editor.
There are two options:
- enable_esessions can be set to Disable to disable it completely
- autonegotiate_esessions can be set to Disable to disable the auto enabling E2E

I'm currently have only autonegotiate_esessions disabled.

**Comment by fuelflo** [comment]
+1

**Comment by GrimKriegor** [comment]
+1

**Comment by cippaciong** [comment]
Please, use [reactions](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) instead of "+1" comments. :+1:

**Comment by GrimKriegor** [comment]
@cippaciong Thank you, sorry for my ignorance.

**Comment by lovetox** [comment]
i made a patch, i hope kalkin has time next week and then i will commit a lot of stuff :)

**Comment by lovetox** [comment]
should be fixed with version 0.7
