### ISSUE TITLE
Text messages are being sent and received but cant be seen

### ISSUE THREAD

**Issue by th3m** [kalkin/gajim-omemo#142]
Omemo encryption works, but in the chat window i cant see any messages being sent or received.

#### General information

* **Gajim Version:**  0.16.6.1
* **Plugin Version:**  0.9.5
* **OS:** Windows 7 32bit

**Comment by lovetox** [comment]
how do you know it works then?
does it happen with all contacts?
where are the messages received, at your end or the other?
can you receive messages?
did your contact trust all your fingerprints?
did you trust the fingerprints of the contact?

**Comment by th3m** [comment]
I have 2 different accounts on jabber.cat, i am testing it using Conversations client. I see the conversation on my Android phone, normally, OMEMO encryption works, the fingerprints are trusted.

Also the OMEMO plugin in Windows seems to work fine, has generated the fingerprint and all the tabs are functioning.

Just the chat window in Windows client doesn't show any text, i can type and send, and my Android is getting it, but the chat window is blank. Also i don't know if that helps, in gajim Linux client there is a red kind of shield on the left, connected with the OMEMO encryption. In Windows client i don't see that.

Update: I think it is not a problem of the OMEMO plugin, but of the client. I ll do more tests.

**Comment by lovetox** [comment]
this should never happen.

look into your user directory
`C:\Users\USERNAME\AppData\Roaming\Gajim`

there should be a `gajim.exe.log` look into it for exceptions and errors
also you could start gajim with `-v`
and look into that log for errors, should be created in the same location

disable all other plugins, and try again.

**Comment by lovetox** [comment]
so did you find something in the log?

**Comment by th3m** [comment]
yes i get this:

No handlers could be found for logger "axolotl.sessionbuilder"
Traceback (most recent call last):
  File "src\common\ged.py", line 93, in raise_event
  File "src\common\connection.py", line 2191, in _nec_stanza_message_outgoing
  File "src\common\connection.py", line 2177, in cb
  File "src\chat_control.py", line 853, in _cb
  File "src\chat_control.py", line 2400, in _on_sent
  File "src\chat_control.py", line 2582, in print_conversation
  File "src\chat_control.py", line 937, in print_conversation_line
  File "src\conversation_textview.py", line 1295, in print_conversation_line
UnicodeDecodeError: 'utf8' codec can't decode byte 0xec in position 10: invalid continuation byte

**Comment by lovetox** [comment]
interesting, seems like a gajim problem to print the message.

did you try to write a message in english without any special characters?

does this sill happen?

**Comment by th3m** [comment]
yes all the tests are being done in English with no special character used. Tried it on another PC with Windows 7 64bit, i am getting the same problem.

On both machines i have installed python 2.7.12 if that helps.

**Comment by lovetox** [comment]
could you go to the preference -> advanced tab -> config editor

and search for "print_time" and set it to "never"

and only to be sure, this happens on every message, encrypted or not

**Comment by th3m** [comment]
i did the step above and now all seem to work fine!

thank you :)
