### ISSUE TITLE
gajim crash on http-upload + OMEMO file transfers on win10 x64

### ISSUE THREAD

**Issue by hubgitbb** [kalkin/gajim-omemo#144]
#### General information

* **Gajim Version:**  0.16.6
* **Plugin Version:**  0.9.7
* **OS:** Windows 10 x64 
* **Server name:** selfhostet prosody
* **Server software:** prosody 0.10 
* **Installed server modules:** smacks, mam, carbons, roster, saslauth, tls, disco, pep, bosh, http, http_upload, posix, throttle_presence

#### Steps to reproduce

1. try sendig file via httpupload button

#### Expected result
expecting gajim sends the file but instead the applications freezes

#### Debug output
dont know how to debug on windows

the debug option seems like it doesent work on windows 
Please start Gajim with `-l gajim.plugin-system.omemo=DEBUG` and post the log file

**Comment by lovetox** [comment]
this is not a gajim bug tracker, please post your issue at the plugin tracker of gajim
https://trac-plugins.gajim.org/report/1

also the omemo plugin has nothing to do with filetransfer (there is no such thing as omemo file encryption, its just basic AES encryption, http upload does this on its own and doesnt use the omemo plugin for it)

on windows you can add the debug command in the properties of the application link under Target, just put it at the end.
or start the application over the command line and put it at the end

-l gajim.plugin-system.httpupload=DEBUG

**Comment by hubgitbb** [comment]
where does gajim put the debug logfiles? i cant find them.

**Comment by lovetox** [comment]
in your user directory
C:\Users\USERNAME\AppData\Roaming\Gajim
