### ISSUE TITLE
Display Verification Barcode

### ISSUE THREAD

**Issue by iNPUTmice** [kalkin/gajim-omemo#146]
Since version 1.15.0 Conversations has the option to verify device fingerprints instead of just trusting them. Verification usually happens through 2D barcodes. While I expect that most verification will happen on mobile devices, if only for the fact that they are portable, it would be extremely helpful if users could verify their own desktop computer. For this reason Gajim should display a 2D barcode somewhere that contains the verification URI.
Verification URIs look as follows:
`xmpp:bob@server.tld?omemo-sid-123456=01deadbeef02034e4...`

Conversations will show Aztec codes but will happily scan QR codes as well. (I think there is a python library for generating QR codes but none for Aztec.)

Users could use Conversations to scan that barcode and verify their desktop’s fingerprint. (From that point forward the 2d barcode in Conversations will also contain the desktop’s fingerprint allowing third parties to verify mobile and desktop at the same point. But that's nothing Gajim needs to be concerned about for now)

**Comment by lovetox** [comment]
is implemented now in 0.9.8
