### ISSUE TITLE
problems with omemo group chat

### ISSUE THREAD

**Issue by whohoho** [kalkin/gajim-omemo#148]
There  is some weird stuff ( not seeing own messages, and not sending encrypted messages for 1 account in group) happening while attempting groupchat with people.

3 of the accounts in the groupchat where in same gajim instance, other one was conversations.

This is the errors that shows up in console, prob. they are not very clear as they are the result of playing around with it for a few hoursf.

<code>

25/11/16 16:49:37 (W) gajim.plugin_system.omemo riseup.net => No devices for jaja@conference.riseup.net
25/11/16 16:49:48 (W) gajim.plugin_system.omemo OMEMO message does not contain our device key
25/11/16 16:49:48 (W) gajim.plugin_system.omemo OMEMO message does not contain our device key
25/11/16 16:49:48 (W) gajim.plugin_system.omemo OMEMO message does not contain our device key
25/11/16 16:49:48 (W) gajim.plugin_system.omemo OMEMO message does not contain our device key
25/11/16 16:49:48 (W) gajim.plugin_system.omemo OMEMO message does not contain our device key
25/11/16 16:49:48 (W) gajim.plugin_system.omemo OMEMO message does not contain our device key
25/11/16 16:49:48 (W) gajim.plugin_system.omemo OMEMO message does not contain our device key
25/11/16 16:49:48 (W) gajim.plugin_system.omemo OMEMO message does not contain our device key
25/11/16 16:49:48 (W) gajim.plugin_system.omemo OMEMO message does not contain our device key
25/11/16 16:49:48 (W) gajim.plugin_system.omemo OMEMO message does not contain our device key

(E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7f71a58d19d0>>
Traceback (most recent call last):
  File "/usr/share/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/usr/share/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/hrk/.local/share/gajim/plugins/omemo/__init__.py", line 387, in message_received
    getJidFromDevice(msg_dict['sid'])
  File "/home/hrk/.local/share/gajim/plugins/omemo/omemo/liteaxolotlstore.py", line 137, in getJidFromDevice
    return self.sessionStore.getJidFromDevice(device_id)
  File "/home/hrk/.local/share/gajim/plugins/omemo/omemo/litesessionstore.py", line 57, in getJidFromDevice
    return result[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
25/11/16 16:53:06 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.message_received of <omemo.OmemoPlugin object at 0x7f71a58d19d0>>
Traceback (most recent call last):
  File "/usr/share/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/usr/share/gajim/src/plugins/helpers.py", line 107, in wrapper
    result = f(*args, **kwargs)
  File "/home/hrk/.local/share/gajim/plugins/omemo/__init__.py", line 387, in message_received
    getJidFromDevice(msg_dict['sid'])
  File "/home/hrk/.local/share/gajim/plugins/omemo/omemo/liteaxolotlstore.py", line 137, in getJidFromDevice
    return self.sessionStore.getJidFromDevice(device_id)
  File "/home/hrk/.local/share/gajim/plugins/omemo/omemo/litesessionstore.py", line 57, in getJidFromDevice
    return result[0]
TypeError: 'NoneType' object has no attribute '__getitem__'

====

25/11/16 16:52:54 (E) gajim.c.ged Error while running an even handler: <bound method Interface.handle_event_gc_invitation of <gui_interface.Interface instance at 0x7f71a65b0e60>>
Traceback (most recent call last):
  File "/usr/share/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/usr/share/gajim/src/gui_interface.py", line 649, in handle_event_gc_invitation
    self.add_event(account, obj.jid_from, event)
  File "/usr/share/gajim/src/gui_interface.py", line 1640, in add_event
    gajim.events.add_event(account, jid, event)
  File "/usr/share/gajim/src/common/events.py", line 247, in add_event
    self.fire_event_added(event)
  File "/usr/share/gajim/src/common/events.py", line 216, in fire_event_added
    listener(event)
  File "/usr/share/gajim/src/chat_control.py", line 3461, in on_event_added
    self._get_gc_invitation(event)
  File "/usr/share/gajim/src/chat_control.py", line 3430, in _get_gc_invitation
    if event.comment:
AttributeError: GcInvitationtEvent instance has no attribute 'comment'

====

</code>

**Comment by whohoho** [comment]
btw. logs are not in order

**Comment by whohoho** [comment]
and this is:
Gajim 0.16.6
omemo 0.9.7

**Comment by lovetox** [comment]
you are aware that every contact has to have every other contact in groupchat in his roster?

check on every account if you have the fingerprints of the all the other contacts

**Comment by jh537** [comment]
I have the same problem. There are only two people in the room with active fingerprints but i can not send text. In 0.16.5 is the text field is not empty and in 0.16.6. It is empty, but the text is then no UI.

**Comment by jh537** [comment]
Ah, I have a non current person banned from the room and now it works again.

**Comment by lovetox** [comment]
btw: 0.16.5 doesnt support omemo groupchat

**Comment by lovetox** [comment]
@whohoho did you solve your problem?

**Comment by whohoho** [comment]
No, but am testing some stuff now.

I have version 0.9.9 of omemo plugin now.

This happens when i create a new room:

01/12/16 22:34:59 (W) gajim.plugin_system.omemo riseup.net => No devices for omemoroom@conference.riseup.net
01/12/16 22:35:10 (E) gajim.c.ged Error while running an even handler: <bound method OmemoPlugin.room_memberlist_received of <omemo.omemoplugin.OmemoPlugin object at 0x7fd0e225b350>>
Traceback (most recent call last):
  File "/usr/share/gajim/src/common/ged.py", line 93, in raise_event
    if handler(*args, **kwargs):
  File "/home/hrk/.local/share/gajim/plugins/omemo/omemoplugin.py", line 460, in room_memberlist_received
    if not jid_known(jid):
  File "/home/hrk/.local/share/gajim/plugins/omemo/omemoplugin.py", line 454, in jid_known
    for nick in self.groupchat[room]:
KeyError: u'omemoroom@conference.riseup.net'

Then i change the settings to closed room, and anyone can see jids.

Then i join the other account, and it lets me enable omemo.

Then the problem is that i can type, but dont see the messages (on both sides).

Also i get this errors in the chat screen:
[22:43:25] ‎Error None: forbidden
‎[22:43:25] ‎Error None: forbidden
‎[22:43:25] ‎Error None: forbidden

**Comment by lovetox** [comment]
@whohoho 
please start gajim -l gajim.plugin_system.omemo=DEBUG
and send me the log output, after you tryed to send some messages

**Comment by whohoho** [comment]
I stripped some stuff from output.

gajim -l gajim.plugin_system.omemo=DEBUG
Logger gajim.plugin_system.omemo level set to 10
01/12/16 23:53:20 (D) gajim.plugin_system.omemo Using fast cryptography
01/12/16 23:53:20 (D) gajim.plugin_system.omemo Disabled Accounts:
01/12/16 23:53:20 (D) gajim.plugin_system.omemo []
/home/hrk/.local/share/gajim/plugins/gotr/ui.py:40: GtkWarning: Unknown property: GtkMenu.ubuntu-local
  self.B.add_from_file(self.GTK_BUILDER_FILE_PATH)

01/12/16 23:53:23 (D) gajim.plugin_system.omemo jabber.systemli.org => Announce Support after Sign In
01/12/16 23:53:23 (I) gajim.plugin_system.omemo jabber.systemli.org => Gajim E2E encryption disabled
01/12/16 23:53:23 (I) gajim.plugin_system.omemo jabber.systemli.org => Roster devices after boot: 
01/12/16 23:53:23 (I) gajim.plugin_system.omemo jabber.systemli.org => Own devices after boot:[]
01/12/16 23:53:23 (D) gajim.plugin_system.omemo jabber.systemli.org => 97 PreKeys available
01/12/16 23:53:23 (I) gajim.plugin_system.omemo jabber.systemli.org => Publishing bundle ...
01/12/16 23:53:23 (I) gajim.plugin_system.omemo jabber.systemli.org => Querry own devicelist ...
01/12/16 23:53:23 (I) gajim.plugin_system.omemo jabber.systemli.org => Received own device list:[386662489]
01/12/16 23:53:23 (I) gajim.plugin_system.omemo jabber.systemli.org => Saved own devices


01/12/16 23:53:26 (I) gajim.plugin_system.omemo riseup.net => Own devices after boot:[]
01/12/16 23:53:26 (D) gajim.plugin_system.omemo riseup.net => 98 PreKeys available
01/12/16 23:53:26 (I) gajim.plugin_system.omemo riseup.net => Publishing bundle ...
01/12/16 23:53:26 (I) gajim.plugin_system.omemo riseup.net => Querry own devicelist ...
01/12/16 23:53:26 (I) gajim.plugin_system.omemo riseup.net => Received own device list:[1064235957]
01/12/16 23:53:26 (I) gajim.plugin_system.omemo riseup.net => Saved own devices
01/12/16 23:53:26 (D) gajim.plugin_system.omemo riseup.net => Adding OMEMO ui for omemoroom@conference.riseup.net
01/12/16 23:53:26 (I) gajim.plugin_system.omemo riseup.net => Publishing bundle was successful

01/12/16 23:53:26 (I) gajim.plugin_system.omemo riseup.net => Received device list for eektoo@jabber.systemli.org:[386662489]
01/12/16 23:53:26 (I) gajim.plugin_system.omemo riseup.net => Saved devices for eektoo@jabber.systemli.org

01/12/16 23:53:27 (D) gajim.plugin_system.omemo OMEMO capable Room found: omemoroom@conference.riseup.net
01/12/16 23:53:27 (D) gajim.plugin_system.omemo Room omemoroom@conference.riseup.net Memberlist received: {u'rachar@riseup.net': {'affiliation': u'owner'}}
01/12/16 23:53:27 (D) gajim.plugin_system.omemo Room omemoroom@conference.riseup.net Memberlist received: {}
01/12/16 23:53:27 (D) gajim.plugin_system.omemo Room omemoroom@conference.riseup.net Memberlist received: {u'eekto@jabber.systemli.org': {'affiliation': u'member'}, u'eektoo@jabber.systemli.org': {'affiliation': u'member'}}
01/12/16 23:53:27 (D) gajim.plugin_system.omemo JID Added: eekto@jabber.systemli.org
01/12/16 23:53:27 (D) gajim.plugin_system.omemo JID Added: eektoo@jabber.systemli.org
01/12/16 23:53:58 (D) gajim.plugin_system.omemo jabber.systemli.org => Adding OMEMO ui for omemoroom@conference.riseup.net
01/12/16 23:53:58 (D) gajim.plugin_system.omemo JID Added: eektoo@jabber.systemli.org
01/12/16 23:53:58 (D) gajim.plugin_system.omemo OMEMO capable Room found: omemoroom@conference.riseup.net
01/12/16 23:54:01 (D) gajim.plugin_system.omemo u'eekto@jabber.systemli.org'
01/12/16 23:54:01 (D) gajim.plugin_system.omemo jabber.systemli.org => Sending Message to omemoroom@conference.riseup.net
01/12/16 23:54:14 (D) gajim.plugin_system.omemo u'eekto@jabber.systemli.org'
01/12/16 23:54:14 (D) gajim.plugin_system.omemo riseup.net => Sending Message to omemoroom@conference.riseup.net
01/12/16 23:54:15 (D) gajim.plugin_system.omemo u'eekto@jabber.systemli.org'
01/12/16 23:54:15 (D) gajim.plugin_system.omemo riseup.net => Sending Message to omemoroom@conference.riseup.net
01/12/16 23:54:20 (D) gajim.plugin_system.omemo u'eekto@jabber.systemli.org'
01/12/16 23:54:20 (D) gajim.plugin_system.omemo riseup.net => Sending Message to omemoroom@conference.riseup.net
01/12/16 23:54:21 (D) gajim.plugin_system.omemo u'eekto@jabber.systemli.org'
01/12/16 23:54:21 (D) gajim.plugin_system.omemo riseup.net => Sending Message to omemoroom@conference.riseup.net
01/12/16 23:54:23 (D) gajim.plugin_system.omemo u'eekto@jabber.systemli.org'
01/12/16 23:54:23 (D) gajim.plugin_system.omemo jabber.systemli.org => Sending Message to omemoroom@conference.riseup.net
01/12/16 23:54:23 (D) gajim.plugin_system.omemo u'eekto@jabber.systemli.org'
01/12/16 23:54:23 (D) gajim.plugin_system.omemo jabber.systemli.org => Sending Message to omemoroom@conference.riseup.net
01/12/16 23:54:24 (D) gajim.plugin_system.omemo u'eekto@jabber.systemli.org'
01/12/16 23:54:24 (D) gajim.plugin_system.omemo jabber.systemli.org => Sending Message to omemoroom@conference.riseup.net
01/12/16 23:54:24 (D) gajim.plugin_system.omemo u'eekto@jabber.systemli.org'
01/12/16 23:54:24 (D) gajim.plugin_system.omemo jabber.systemli.org => Sending Message to omemoroom@conference.riseup.net
 

01/12/16 23:55:05 (D) gajim.plugin_system.omemo jabber.systemli.org => Disable OMEMO for omemoroom@conference.riseup.net
01/12/16 23:55:10 (D) gajim.plugin_system.omemo jabber.systemli.org => Sending Message to omemoroom@conference.riseup.net
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
01/12/16 23:55:15 (D) gajim.plugin_system.omemo riseup.net => Disable OMEMO for omemoroom@conference.riseup.net
01/12/16 23:55:16 (D) gajim.plugin_system.omemo riseup.net => Sending Message to omemoroom@conference.riseup.net
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
01/12/16 23:55:17 (D) gajim.plugin_system.omemo riseup.net => Sending Message to omemoroom@conference.riseup.net
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
01/12/16 23:55:21 (D) gajim.plugin_system.omemo riseup.net => Enable OMEMO for omemoroom@conference.riseup.net
01/12/16 23:55:22 (D) gajim.plugin_system.omemo u'eekto@jabber.systemli.org'
01/12/16 23:55:22 (D) gajim.plugin_system.omemo riseup.net => Sending Message to omemoroom@conference.riseup.net
01/12/16 23:55:30 (D) gajim.plugin_system.omemo jabber.systemli.org => Enable OMEMO for omemoroom@conference.riseup.net
01/12/16 23:55:31 (D) gajim.plugin_system.omemo u'eekto@jabber.systemli.org'
01/12/16 23:55:31 (D) gajim.plugin_system.omemo jabber.systemli.org => Sending Message to omemoroom@conference.riseup.net

**Comment by lovetox** [comment]
hm ok i will look into this in the next days, something is not working correctly

**Comment by jh537** [comment]
yes, solved



Jan-Hendrik Franz 
Oberer Gutsweg 14A
09212 Limbach-Oberfrohna
 Tel.: +49 (0) 3722 76 45 104
Mobil:+49 (0) 1515 14 55 355
XMPP-OMEMO: jh@gleisnetze.de
-----Ursprüngliche Nachricht-----
Von: lovetox <notifications@github.com>
Gesendet: Mon 28 November 2016 17:43
An: omemo/gajim-omemo <gajim-omemo@noreply.github.com>
CC: jh <563757@gleisnetze.de>; Comment <comment@noreply.github.com>
Betreff: Re: [omemo/gajim-omemo] problems with omemo group chat (#148)

@whohoho did you solve your problem?

**Comment by eNTi** [comment]
Having EXACTLY the same issue. Is this plugin still being maintained?

I suppose those are pulseaudio errors?
```
Connection failure: Connection refused
pa_context_connect() failed: Connection refused
```

**Comment by lovetox** [comment]
your errors have nothing to do with omemo

please read https://github.com/omemo/gajim-omemo
and report problems you have to the new bug tracker.
