### ISSUE TITLE
Omemo fingerprints empty

### ISSUE THREAD

**Issue by kopfteil** [kalkin/gajim-omemo#151]
Hi,

I can't get Omemo to run on my server. I have two separate machines with gajim 16.6 on each of them and a prosody server (also tried openfire and ejabberd) and i finally managed to get the OMEMO icon to even show up in the chat window. Before i got errors related to no finding the client list:

> 01/04/2017 23:59:09 (W) gajim.plugin_system.omemo somehost => No devices for milpstein@somehost

Now the button shows up but the there are no fingerprints, the windows are empty and only show their own fingerprint. How do i solve that?

Writing test messages between the users does not change anything.

The server does however use some selfsigned certificate, but that shouldn't interfere?

Starting gajim with -l gajim.plugin_system.omemo=DEBUG yields the following output:
```

Logger gajim.plugin_system.omemo level set to 10
01/05/2017 00:02:30 (D) gajim.plugin_system.omemo Using fast cryptography
/usr/lib/python2.7/pkgutil.py:186: ImportWarning: Not importing directory '/usr/local/lib/python2.7/dist-packages/google': missing __init__.py
  file, filename, etc = imp.find_module(subname, path)
01/05/2017 00:02:30 (D) gajim.plugin_system.omemo Disabled Accounts:
01/05/2017 00:02:30 (D) gajim.plugin_system.omemo []
01/05/2017 00:02:30 (I) gajim.plugin_system.omemo hostname => Gajim E2E encryption disabled
01/05/2017 00:02:30 (I) gajim.plugin_system.omemo hostname => Roster devices after boot:{}
01/05/2017 00:02:30 (I) gajim.plugin_system.omemo hostname => Own devices after boot:[]
01/05/2017 00:02:30 (D) gajim.plugin_system.omemo hostname => 100 PreKeys available
01/05/2017 00:02:30 (D) gajim.plugin_system.omemo hostname => Adding OMEMO ui for milpbfw@hostname
01/05/2017 00:02:48 (D) gajim.plugin_system.omemo hostname => Announce Support after Sign In
01/05/2017 00:02:48 (I) gajim.plugin_system.omemo hostname => Publishing bundle ...
01/05/2017 00:02:48 (I) gajim.plugin_system.omemo hostname => Querry own devicelist ...
01/05/2017 00:02:48 (I) gajim.plugin_system.omemo hostname => Received own device list:[192218474, 412754902, 15427766]
01/05/2017 00:02:48 (I) gajim.plugin_system.omemo hostname => Saved own devices
01/05/2017 00:02:48 (I) gajim.plugin_system.omemo hostname => Received device list for milpbfw@hostname:[1923853667]
01/05/2017 00:02:48 (I) gajim.plugin_system.omemo hostname => Saved devices for milpbfw@hostname
01/05/2017 00:02:48 (I) gajim.plugin_system.omemo hostname => Publishing bundle was successful
01/05/2017 00:03:23 (D) gajim.plugin_system.omemo hostname => Announce Support after Sign In
01/05/2017 00:03:23 (I) gajim.plugin_system.omemo hostname => Publishing bundle ...
01/05/2017 00:03:23 (I) gajim.plugin_system.omemo hostname => Querry own devicelist ...
01/05/2017 00:03:23 (I) gajim.plugin_system.omemo hostname => Received own device list:[192218474, 412754902, 15427766]
01/05/2017 00:03:23 (I) gajim.plugin_system.omemo hostname => Saved own devices
01/05/2017 00:03:23 (I) gajim.plugin_system.omemo hostname => Received device list for milpbfw@hostname:[1923853667]
01/05/2017 00:03:23 (I) gajim.plugin_system.omemo hostname => Saved devices for milpbfw@hostname
01/05/2017 00:03:23 (I) gajim.plugin_system.omemo hostname => Publishing bundle was successful
01/05/2017 00:03:28 (D) gajim.plugin_system.omemo hostname => Adding OMEMO ui for milpbfw@hostname
```

**Comment by lovetox** [comment]
01/05/2017 00:03:23 (I) gajim.plugin_system.omemo hostname => Saved devices for milpbfw@hostname

frist check the icon and see if the checkbox is activated
then try and write a message
look at the log output right after writing the message

**Comment by lovetox** [comment]
you sent me a log output but 
milpstein@somehost
is not in there

**Comment by lovetox** [comment]
Also a log from both machines would be good, on the one you just posted everything looks good

**Comment by kopfteil** [comment]
Hi lovetox,
I will post the logs of both sides later today.

> frist check the icon and see if the checkbox is activated
> then try and write a message
> look at the log output right after writing the message

This does not work since there are no fingerprints in the fingerprints submenu for me to trust, it's simply empty and contains only the own fingerprint.

**Comment by lovetox** [comment]
thats expected, fingerprints in the window will only be pulled from the server when you actually try to send a message.

if the pull from the server doesnt work after sending the message, it will show in the logs

**Comment by kopfteil** [comment]
I was just getting ready to take screenshots for you as i started the same setup with prosody and the clients that i used the last two days to no avail, suddenly the fingerprints show up in the menus, even on conversations. It all works now. I absolutely can't tell why it works now and didn't yesterday, but i'll go with that. 

So i guess this can be closed. Thanks for your time.

**Comment by lovetox** [comment]
@kopfteil from my experience, i didnt find a bug with publishing and getting keys/devices for a long time.

if it doesnt work in the future, i would say you gain more if you try and see what is published on the servers nodes and if the server really sends this stuff to other clients. watch the xml at startup.
the process of publishing and getting keys for the client is pretty easy and not so error prone.

but often the servers just dont propagate updates to other clients, im sure there are still some bugs to discover serverside
