### ISSUE TITLE
Omemo Keys should remain activated by server-new start

### ISSUE THREAD

**Issue by jh537** [kalkin/gajim-omemo#152]
Wenn der Server neu gestartet wird sollten in Conversations die Omemo-Schlüssel wie vor dem Neustart aktiviert bleiben. Ansonsten werden Nachrichten von und zu Clienten mit deaktivierten Keys (z. B. bei Gajim Deskop) nicht angezeigt.  Der Nutzer ist verwunden bzw. verärgert. Damit ließe sich dann auch öfters der XMPP-Server neu starten z. B. nach Update des Prosody.  Sorry, wenn ich es falsch eingeordnet habe. Aber Prosody hat ja eigentlich nix damit zu tun, da OMEMO nur client-seitig arbeitet oder hier vielleicht doch?       

If the server is restarted the Omemo keys like before the new start should remain in Conversations activated. Otherwise news from and to Clienten with deactivated Keys is not indicated (e.g., with Gajim Deskop). The user is wound or annoys. Then with it the XMPP server can be also begun on occasion anew, e.g., after update of the Prosody. Sorry if I have wrong arranged it. But Prosody deals, actually, nothing with it, because OMEMO works only client-sided or here maybe, nevertheless?

**Comment by klemens** [comment]
This is a server side issue, as PEP is used to store the keys on the server (so you can write messages to contacts that are offline). Currently prosody only stores these in memory, but this will hopefully change soon: https://prosody.im/issues/issue/485

Also this is not the correct issue tracker, the plugin is now part of the gajim-plugins repository: https://dev.gajim.org/gajim/gajim-plugins

**Comment by lovetox** [comment]
thanks @klemens for summarizing this.

yes omemo keys are stored on the server, prosody deletes the keys on restart.
conversations displays the keys correctly as inactive because they are not on the server anymore.
