### ISSUE TITLE
omemo fehler

### ISSUE THREAD

**Issue by ghost** [kalkin/gajim-omemo#16]
Fehler bei OMEMO version aus dem GIT vom 03.01.2016
Gajim 0.16.4
installation wie im GIT beschrieben per GIT und PIP unter Arch
![screen_20160103-202845](https://cloud.githubusercontent.com/assets/4246860/12080431/d91bf13a-b259-11e5-954b-07266eb1fbd7.png)

**Comment by piratenpanda** [comment]
Already reported this issue with the comment "It's already known" but I guess it's never bad to have it reported here as well :)

https://trac.gajim.org/ticket/8208#comment:1

**Comment by kalkin** [comment]
Hi thank you guys for reporting. Work is in progress

**Comment by kalkin** [comment]
This issue should be fixed in the current HEAD
