### ISSUE TITLE
option to enable omemo on default

### ISSUE THREAD

**Issue by tristan-k** [kalkin/gajim-omemo#17]
Everytime I restart Gajim I will have to reenable the OMEMO checkbox. Please add an option to activate OMEMO on default.

**Comment by kalkin** [comment]
Hi,

thank you for you report. Work in Progress.

**Comment by RalfJung** [comment]
Ideally, this could be a per-contact/per-conversation state.

**Comment by kalkin** [comment]
@RalfJung yes it's per contact.
