### ISSUE TITLE
Images sent using HttpUpload are not encrypted

### ISSUE THREAD

**Issue by cippaciong** [kalkin/gajim-omemo#19]
Images sent using HttpUpload are not encrypted, at the same time, images that are received encrypted (sent for example from Conversations) are not visible.

**Comment by kalkin** [comment]
I'm not sure yet if I need to fix it in my plugin or if it is a http-file-upload plugin issue, or both. Would be great if you could make some research and perhaps even some code to fix the issue _prettyplease_ :pray: ?. 

I'm currently reworking the omemo library so we have tests and it can be reused by other clients, see also [omemo/python-omemo](/omemo/python-omemo), so it could take some time till I can fix this issue.

**Comment by lovetox** [comment]
images i receive from conversations encrypted with omemo are not valid links
the decryption doesnt work somehow

i get
The image “ https://accountjabberat/media/http_upload/mMByU4PZDo8jBwGoppIc6bU4qdnO6ph6/0_bigjpg#6c62559db803b9c0050b96bf9553ab22d536ca3c77ad49ebb7e8808e866adc5e993371afee5695791c7f7d3b5b44ae70” cannot be displayed because it contains errors"

if i send a image unencrypted from conversations it works.

**Comment by kalkin** [comment]
AFAIK @tmolitor is currently working on fixing the gajim http-file-upload plugin. We shall wait a little bit.

**Comment by lovetox** [comment]
so fixing gajim http upload plugin to use encryption is only one issue described here.

the second is that omemo doesnt decrypt the message with the link to the file correctly if sent from conversations. i get a link but it points to an invalid address.

**Comment by iNPUTmice** [comment]
@lovetox you can use my [ImageDownloader](https://github.com/iNPUTmice/ImageDownloader) to decrypt the image link. I'm combining that with an [openbrowser wrapper](https://gist.github.com/iNPUTmice/b5667a61d17bffb33c23) (change the browser in the gajim settings to that script) and it magically opens the image when you click on the link.

(Not an actual solution for the problem but a pretty good workaround imho)

**Comment by lovetox** [comment]
@iNPUTmice thanks i will try this. 

just out of curiosity
why are the links conversation produces longer and different in format? is there some added security involved?

EDIT: haha sorry i just read this
`When Conversations uploads an encrypted image with XEP-0363: HTTP Upload it appends the encryption key as an anchor to the URL.`

**Comment by iNPUTmice** [comment]
> why are the links conversation produces longer and different in format? is there some added security involved?

longer and different compared to what? The Readme in that repo has a small explanation of the crypto involved.

**Comment by lovetox** [comment]
yeah clicked the link after writing the message, thanks i will try this :)

**Comment by ao2** [comment]
Hi, I ported the useful downloader proposed by @iNPUTmice to pyhton:
https://git.ao2.it/conversations_http_downloader.git/

I think a python solution it's easier to deploy for gajim users on the desktop.

**Comment by lovetox** [comment]
So now that i looked into this

right now the http `http upload` adds XHTML to the stanza which is not ecrypted.
i patched the OMEMO Plugin to remove every xhtml before a message gets sent, and will make a pull request for that soon.

so then the link which `http upload` generates is like a normal message which is fully encrypted by the plugin.

what @cippaciong probably means is that the picture is not encrypted on the server.
the omemo plugin has nothing to do with the picture upload to the server, it only sends the link.

so in my opinion this should be handled from the `http upload` plugin.

the same goes for decrypting the picture. this is already handled by the the `url_image_preview` plugin
altough rather slow, but a better solution is in the works.

so i would consider this solved from OMEMO side.

**Comment by cippaciong** [comment]
> what @cippaciong probably means is that the picture is not encrypted on the server.
> the omemo plugin has nothing to do with the picture upload to the server, it only sends the link.
> 
> so in my opinion this should be handled from the http upload plugin.

When I opened this issue I hadn't clear in my mind which plugin should do what, but by now it's clear that the entire image encryption/decryption should be done by the http upload plugin and its developer is already working on it afaik.
Feel free to close the issue. :+1:

**Comment by ao2** [comment]
Just a side note, a standalone downloader/decrypter is still a valid workaround for the case when a contact using Conversations uploads a **voice** message using HTTP Upload, AFICT there's no plugin that handles voice messages for gajim.

**Comment by kalkin** [comment]
May be http-file-upload plugin should just call `xdg-open` on the downloaded file? But this probably will only work on Linux.

**Comment by ao2** [comment]
@kalkin AFAICS gajim already uses `xdg-open` (or other mechanisms on other systems) to open local files: https://trac.gajim.org/browser/src/common/helpers.py#L718 so maybe this can be reused: some plugin can detect if the URL of the encrypted file is in the Conversations format (i.e. with a 96 characters long anchor, containing the key and IV) and then perform some actions, like one of the following:
- download and decrypt the file (like `url_image_preview` does) and replace the URL with a `file://` URL. This is transparent but implicit and the user would have little control on the local decrypted copy. Also I am not sure how this would work with old messages from the log.
- add a button to download and open the file explicitly (maybe with an option to delete the local copy?)

Just ideas, sorry, I am afraid I won't be able to do experiments about that myself anytime soon.

**Comment by lovetox** [comment]
We will definitly build in a cache, or else everytime you open the chat window or history window, it would start downloading and decrypting again. and i think it wouldnt be hard to decrypt all pictures to harddisk, a folder you choose in the config menu

**Comment by lovetox** [comment]
i reopend this so no more new issues about the same thing are opended

**Comment by lovetox** [comment]
just a little update

the newest version of httpupload 0.4.0 from the gajim plugin store, supports encrypted upload for linux systems.

an encrypted upload is made automatically when the omemo encryption is active with a client.

**Comment by cippaciong** [comment]
I have updated the httpupload plugin today and tested with a couple of images, it worked pretty well. Thanks!

**Comment by dllud** [comment]
@lovetox Working here too. Thanks!
I think this issue can now be closed. We should open a new one for the download & decrypt functionality.

I agree with @ao2 :

> gajim already uses xdg-open [...] to open local files [...] so maybe this can be reused: some plugin can detect if the URL of the encrypted file is in the Conversations format [...] and then perform some actions

Which plugin should be responsible for this, i.e., where should we open the new issue? [httpupload](https://trac-plugins.gajim.org/wiki/HttpUploadPlugin)? This seems more like httpdownload :smile:.

**Comment by lovetox** [comment]
you dont need to open a new issue, im working on it already :)

**Comment by tristan-k** [comment]
> ... supports encrypted upload for linux systems.

Will there be window support as well?

**Comment by lovetox** [comment]
yes eventually, gajim maintainer has to pack the dependencys into the installer.
i already talked to him about it.

**Comment by lovetox** [comment]
update: the Url Image Preview Plugin of Gajim can decrypt images now and show them.
again only on linux systems for now

the image is nowhere saved, so it cant be found on the harddisk for now, only inline preview in the chat window

@tristan-k if you are interested i could write steps down that you can make this work on windows also

**Comment by tristan-k** [comment]
@lovetox Of course. Knock yourself out!

**Comment by lovetox** [comment]
https://github.com/omemo/gajim-omemo/wiki/Making-Cryptography-Package-available-on-Windows

after that you have to edit
`httpupload.py` and `url_image_preview.py`
search for this line
`if os.name != 'nt':`

and make it

`if os.name == 'nt':`

hope that works :)

**Comment by tristan-k** [comment]
Much appreciated. Will report back.

**Comment by lovetox** [comment]
@tristan-k can you scrap all those changes, and just try to edit the .py file and try if it works?

**Comment by lovetox** [comment]
@tristan-k foget it, i found the issue why its not working on windows, i will release updates to both plugins soon

**Comment by lovetox** [comment]
@tristan-k i pushed a new version of the image_preview_plugin, it should now decrypt, omemo send pictures in an instant :)

http upload will follow soon

**Comment by tristan-k** [comment]
@lovetox Thanks!

**Comment by lovetox** [comment]
The new version of `url_image_preview` plugin, decrypts automatically pictures stores it to a download folder on the harddisk, and displays a thumbnail in chat.

if you click the thumbnail, the picture is opened from the harddisk,

**Comment by lovetox** [comment]
http upload now supports upload of encrypted files when omemo is activated, on windows and on linux.

so i close this for now.

**Comment by ao2** [comment]
@lovetox thanks.

Any long term plans to support opening encrypted uploads that are not images?
For example, Conversations shows an "Open" button in this case instead of the preview of the image.

In a message above it was proposed to generalize the `url_image_preview` plugin into something like `http_download`.

**Comment by lovetox** [comment]
yeah this is planned, we layed the groundwork for that now.

pictures up to 10 MB are downloaded and stored on the harddisk already.
so theoretical we only have to add the allowed extensions to download and open PDFs for example. and show a file icon instead of the previewed picture.

**Comment by ao2** [comment]
OK, great. If you open an issue somewhere to track the development please post a link here.

**Comment by raveer** [comment]
Do I need to setup anything to decode the encrypted sent files? I am able to upload encrypted pdfs or txts (the ones I tried), but neither user (sender and recipient) can decrypt them with a click on the link in the chat window whether the file is saved to disk or opened with external program from dialog. I am using gajim nightly 20160908-1 with the following plugins: httpupload 0.4.1, omemo 0.9.0 and url image preview 0.9.4.

**Comment by ao2** [comment]
@raveer until there is a more integrated solution you can work around the issue by using something like this: https://git.ao2.it/conversations_http_downloader.git/

Either by pasting the link on the command line or by setting up the URL opener in gajim to the wrapper script created after running `make` in `conversations_http_downloader`

**Comment by raveer** [comment]
@ao2 thank you for the work around.

**Comment by andreygursky** [comment]
Hi, since it is the main bug report about file transfers, I'd ask here. After an image gets successfully transferred from recent Gajim with OMEMO (without HttpUpload) and downloaded by Conversations client, the later marks it as being sent not encrypted. Does OMEMO plugin not yet support OMEMO Jingle (https://conversations.im/xeps/omemo-filetransfer.html) and silently sends plain data away?

@iNPUTmice, I suppose, Conversations already supports this, doesn't it? Is it possible to choose on which way a file will be transferred: OMEMO Jingle or HttpUpload?

**Comment by iNPUTmice** [comment]
@andreygursky No Gajim does not use OMEMO encryption when using Jingle.

Conversations will always prefer HTTP Upload when available.

**Comment by andreygursky** [comment]
@iNPUTmice, thanks for clarification. Is the status of such Gajim (adding additional hooks for file transfer to be handled by gajim-omemo?) improvement already being tracked somewhere? And is a corresponding option considered for Conversations (at least in advanced mode or so)?

**Comment by iNPUTmice** [comment]
> And is a corresponding option considered for Conversations (at least in advanced mode or so)?

No. And I don't see a reason why anyone would prefer jingle over HTTP for encrypted transfers.

And the same probably goes for Gajim; Just use HTTP upload.

**Comment by andreygursky** [comment]
Thanks for the advice. I see at least 2 advantages of HttpUpload: offline availability and more robust transfer (since it is splitted in 2 phases: upload and download). But I was sure, Jingle must have its own advantages, while HttpUpload was implemented as a workaround. So this file size limit (10 MB) doesn't come from HttpUpload itself?

**Comment by iNPUTmice** [comment]
Conversations will fall back to Jingle if the file is too large. But in general it is advisable to just raise the limit for HTTP Uploaded files on the server side.

**Comment by andreygursky** [comment]
Is it possible to query this limit when I'm using not my own server? I think Gajim allows it through XMPP Console, but maybe it can be seen in log?

**Comment by andreygursky** [comment]
I've asked that, because it seemed the server wouldn't support such advertisement. It turned out, I've been trapped in the outdated XEP on the Conversations server: https://conversations.im/xeps/xep-http-upload.html. Since version 0.2 the maximum file size should be announced.

**Comment by ahmetsevinc77** [comment]
@ao2 , can you please explain how to set up the URL opener in gajim for this to work.

**Comment by ao2** [comment]
@ahmetsevinc77 I added some instructions in the README file:
https://git.ao2.it/conversations_http_downloader.git/blob/HEAD:/README#l24

**Comment by ahmetsevinc77** [comment]
@ao2 thanks for that. I got it working. Is it too dificult to add some kind of progress bar showing the download status? On small files it opens pretty much instantly but on bigger files you are left wondering is it doing anything at all and sometimes double and triple click on it the url..

**Comment by ao2** [comment]
@ahmetsevinc77 the open_wrapper.sh in conversations_http_downloader is just a quick workaround to have things working **somehow**, I don't plan to extend it in any way.

Eventually a gajim plugin will do this, and that might provide a progress bar, or at least some indication that a big download has started.

BTW the image_preview plugin should already support encrypted images, and I read here that there are plans for a more generic plugin which would support also other file types.

**Comment by Prajjwal** [comment]
Is there an ETA on getting gajim to decrypt OMEMO *file* transfers? I got the `conversations_http_downloader` script off ao2's comment, but it is impossible to get my contacts to use it unless they can use it inline. A `right_click -> open / save` option would be nice. I'd implement it myself, but not a python programmer. :(

The `image_preview` plugin does support images, but I'd like a way to be able to decrypt images without being shown inline thumbnails. Currently working around this by making the preview size 10x10 pixels. Sounds like decryption is something `gajim_omemo` should handle, because a lot of people, including me, don't always want to see inline previews.

**Comment by lovetox** [comment]
no there is no ETA.
PR are welcome.
development happens at dev.gajim.org
