### ISSUE TITLE
Sometims incoming messages are only shown as a notification, not in the conversation

### ISSUE THREAD

**Issue by RalfJung** [kalkin/gajim-omemo#21]
The title pretty much says it all: Sometimes when I receive an OMEMO message for a conversation that is in background, I _do_ get a notification for it on my screen. However, when I then select the tab with that conversation, there is no new message. My phone shows the message.

**Comment by kalkin** [comment]
@RalfJung 
Thank you for your report. I and other people had experienced the same issue until now, I always thought this is a bug in Gajim, but you say it definitely happens only when using OMEMO?

**Comment by RalfJung** [comment]
I have not seen this happen ever before I installed OMEMO. And I also have not seen this happen in conversations that do not use OMEMO. That's all I can say ;-)

**Comment by kalkin** [comment]
@RalfJung Ok you convienced me.

**Comment by kalkin** [comment]
@RalfJung according to Asterix in the gajim MUC this could be a bug in Gajim. This [patch](https://github.com/kalkin/gajim/commit/4fed7b7cce05e03ab541c6d2154c0eb8e390191e) should fix it.

**Comment by RalfJung** [comment]
I saw an error on the console a few times today saying that `LOG_DB_PATH` is not an attribute of something. So, this patch most likely fixes something. However, I did not see lost messages today, so I am not sure if that's related. I can't reproduce lost messages anyway, so I have no way to test :-/

**Comment by kalkin** [comment]
This is fixed in the current HEAD. The issue was that we did not convert the OMEMO decryption output to unicode, but sqlite3 expects unicode.

**Comment by RalfJung** [comment]
May this also be the reason for the occasional message that my Log DB is broken? I just ignored it so far, hoping that my log DB is not actually broken^^

**Comment by kalkin** [comment]
@RalfJung Yes. DB is not broken, but some omemo encrypted messages are not saved.
