### ISSUE TITLE
Python OMEMO package

### ISSUE THREAD

**Issue by daradib** [kalkin/gajim-omemo#22]
What are your thoughts on moving/copying non-gajim code to a separate omemo package that can be used by other python software? For example, aes_gcm, state, store.

I know that it's more trouble, so I don't have any expectations, just wondering if you had an idea in mind. And thanks for the plugin!

**Comment by kalkin** [comment]
Yes i had this idea. It's a good idea. Needs only to be executed. Few notes:
- OmemoState needs probably clean up.
- The trust managment handling needs to be added

Patches are welcome :grinning:

**Comment by kalkin** [comment]
Perhaps it  would also make sense to abstract away the UI states i.e: are there prekeys missing? if so how many? Is omemo active right now?

**Comment by kalkin** [comment]
@daradib I started separating an OMEMO library from the gajim-omemo plugin. Please have at https://github.com/omemo/python-omemo Help is wanted
