### ISSUE TITLE
'ChatControl' object has no attribute 'lock_image'

### ISSUE THREAD

**Issue by RalfJung** [kalkin/gajim-omemo#24]
I just got this Python error:

```
Traceback (most recent call last):
  File "/home/r/.local/share/gajim/plugins/omemo/ui.py", line 78, in on_click
    self.chat_control._show_lock_image(True, 'OMEMO', True, True, True)
  File "/home/r/src/gajim/src/chat_control.py", line 2317, in _show_lock_image
    self.lock_image.set_from_file(img_path)
AttributeError: 'ChatControl' object has no attribute 'lock_image'
```

What I did:
- I received an OMEMO message for a closed conversation
- I double-clicked that contact in the buddy list
- Then the error appeared

**Comment by kalkin** [comment]
Please try the current master.

**Comment by RalfJung** [comment]
I was slightly hesitant to update, since I was unsure how stable master is... but I guess even the "stable" versions are kind of experimental ;-)

**Comment by RalfJung** [comment]
I just did the same think, and with the git master version, there was no error.
