### ISSUE TITLE
Bad unicode (?) icon when OMEMO encyption starts

### ISSUE THREAD

**Issue by RalfJung** [kalkin/gajim-omemo#25]
The chat message logged when OMEMO encryption starts includes a broken Unicode icon here on my Debian testing system:

```
‎[15:58:20] ‎🔒 OMEMO encryption enabled
```

The character before "OMEMO" is an "unknown character" box.

This only started when I upgraded from version 0.2 to the git master.

**Comment by kalkin** [comment]
Ok, I went a little bit fancy and added a unicode `LOCK` and `LOCK_OPEN`, but they probably depend on your font. Will remove it.

**Comment by cippaciong** [comment]
Why don't you make that optional instead? The lock symbol seems a rather good idea to me and having the Symbola font should be enough to see the correct character (or not?).

**Comment by kalkin** [comment]
@cippaciong Because it's a hack for missing ui components in Gajim. This should be solved by Gajim
