### ISSUE TITLE
Misleading warnings: No OMEMO dev_keys

### ISSUE THREAD

**Issue by RalfJung** [kalkin/gajim-omemo#27]
For conversations that are opened immediately when Gajim starts (because they were open last time), OMEMO prints

```
jabber.ralfj.de ⇒ No OMEMO dev_keys for contact@server
```

even if that contact _does_ have OMEMO keys - actually, keys that the plugin even knows about. OMEMO seems to work fine in these conversations nevertheless.

**Comment by kalkin** [comment]
Currently it needs to fetch all the existing dev_keys from the server, even if it knows them already and there are already in the database. This is a known limitation and I'm working on it at [/omemo/python-omemo](/omemo/python-omemo)

**Comment by RalfJung** [comment]
Well, the confusing bit is that later on, it does find OMEMO dev_keys for that contact. (Which is nit printed, because that's at level info or debug). So the statement that these contacts have no OMEMO dev_keys is just wrong - actually, it's just so early in the login process that Gajim hasn't yet loaded them.

**Comment by iNPUTmice** [comment]
should be fixed by f65ad71b67a7bad5de7dc84e322ca3b3f0911141
