### ISSUE TITLE
Gajim doesn't crypt messages

### ISSUE THREAD

**Issue by zzottel** [kalkin/gajim-omemo#3]
I just installed the plugin from current git.

I received the keys (button shows "clear devices" now), and when the other end writes an OMEMO-encrypted message, I can read it.

However, regardless of whether the check next to OMEMO is set or not, Gajim always sends unencrypted messages.

Gajim version 0.16 on Lubuntu.

**Comment by zzottel** [comment]
Also tried with debugging switched on as described in the README. When I send a message, the plugin doesn't log anything at all, it seems it isn't called at that moment.

**Comment by kalkin** [comment]
Hi,

Before the commits made today you had to patch gajim to get the OMEMO plugin properly working. Perhaps you have not applied the patch? Please check out and test the current HEAD.

> Also tried with debugging switched on as described in the README. When I send a message, the plugin doesn't log anything at all, it seems it isn't called at that moment.

This is strange, if you see the "Clear Devices" or the "Prekey" button, the plugin is active. Can you please try to run gajim with the `-v` switch and see if there is any OMEMO output?

> However, regardless of whether the check next to OMEMO is set or not, Gajim always sends unencrypted messages.

How did you check that the message send is unencrypted? When the message is shown in Conversations, does it have no :lock: symbol or is it just rest?

**Comment by zzottel** [comment]
Hi,

I only first installed when the patch was not required anymore. I just pulled again and was already up to date (hadn't pulled in between, so I've been on the now current version from the beginning).

gajim -v produces lots of output, among them OMEMO-related stuff, yes.

When I send a message using Gajim, the OMEMO plugin doesn't log anything in debug mode. In my own Conversations, the messages are shown without a padlock. In my contact's Conversations, the messages are shown in red and without a padlock.

Decryption works, I can see encrypted messages from my contact and now also from my own Conversations (see my comment to #4 ). But I can't send encrypted messages from Gajim.

**Comment by kalkin** [comment]
> When I send a message using Gajim, the OMEMO plugin doesn't log anything in debug mode.

Hmm, please try running with `-l gajim.plugin_system.omemo=DEBUG`. The README omits the `gajim.` part. May be this is an issue. It works for me without the `gajim` prefix, but may be this is an issue on your system?

> In my own Conversations, the messages are shown without a padlock. In my contact's Conversations, the messages are shown in red and without a padlock.

This is very strange. Can you please post the debug output here?

Also which exact version of gajim do you use? I am using _16.4_. If you are using an older version you can check out gajim _16.4_ from repository, like this: 

``` shell
hg clone https://hg.gajim.org/gajim
cd gajim
hg update gajim-0.16.4 --clean
```

Thank you for your help!

**Comment by zzottel** [comment]
That was it, thanks.

I was using the Gajim that comes with Ubuntu 15.04. I don't know what version exactly that is, didn't find a dialog or command line option of Gajim itself that would tell me. The Ubuntu package version is 0.16-1.

With 0.16.4 from the Mercurial repository, it works.
