### ISSUE TITLE
OMEMO not available when writing message to other resource

### ISSUE THREAD

**Issue by akallabeth** [kalkin/gajim-omemo#32]
When sending a message to another resource from gajim no OMEMO encryption is available.

**Comment by kalkin** [comment]
1. OMEMO is designed to be used together with MAM and Carbons, so there should not be any reason to send a message to another resource, or is there? What's your use case (I am genuinely interested)?
2. I just tried opening an conversation with a specific resource (Right click in the buddy list -> Start Chat ...). It shows the OMEMO checkbox and everything looks fine to me. Are you using an up to date version of the plugin?

**Comment by akallabeth** [comment]
Maybe I was not clear enough in my initial description.

I'm trying to send a message from my desktop (running gajim) to my mobile running conversations. (same account)
It works when sending to somebody else and selecting a specific resource, but not if sending to oneself.

**Comment by kalkin** [comment]
@akallabeth Thank you for your explanation.I found the issue, but I'm currently on my mobile. Here at [line 239](https://github.com/omemo/gajim-omemo/blob/master/__init__.py#L239) ~~you need to add to the check if the `contact_jid` is in `state.own_devices`~~

EDIT: The line i mentioned is important, but the approach is wrong.
