### ISSUE TITLE
GUI inconsistent

### ISSUE THREAD

**Issue by chaoscommander** [kalkin/gajim-omemo#35]
Just trying OMEMO with Gajim 0.16.5. Following problem: I have two chat tabs open, both with Conversations users. One shows the on/off checkbox and the shield symbol, the other doesn't. The second guy tells me my messages arrive encrypted with OMEMO, my GUI however looks like OMEMO isn't even available. In case this is relevant: the first user (with correct behaviour) has only one device key, the other has multiple.

**Comment by chaoscommander** [comment]
... I need to restart Gajim after opening a conversation with an additional contact in order to enable the OMEMO buttons. For every contact I want to first initiate OMEMO encryption with.

**Comment by kalkin** [comment]
This issue should be solved. I will close it, please feel free to comment if you are still experiencing it and i will reopen it.
