### ISSUE TITLE
No posibility to compare keys and selectively allow disalow devices

### ISSUE THREAD

**Issue by kertase** [kalkin/gajim-omemo#38]
There is no menu to compare the keys and to chose what keys should be used and which should not.

**Comment by kalkin** [comment]
This is known. Feel free to make a PR if it's really important to you. If not just wait till I implement it someday :)

**Comment by kertase** [comment]
Just noting :), from a secure point of view this is a critical issue.

**Comment by kalkin** [comment]
> Just noting :), from a secure point of view this a critical issue.

FULL ACK :+1:

**Comment by Mikaela** [comment]
This also makes maintaining list of your keys on your website quite difficult as you have no idea what the fingerprints are and it's not as reliable to just check what fingerprints other client (Conversations).

**Comment by kalkin** [comment]
Closing this, because @lovetox added a fingerprint ui
