### ISSUE TITLE
no OMEMO with OMEMO-capable contacts on some servers

### ISSUE THREAD

**Issue by oodbur** [kalkin/gajim-omemo#39]
I use Gajim v0.16.5, OMEMO plugin v0.4 (same situation with 0.16/0.3).
For one contact that has OMEMO-enabled client software (Gajim with same versions or Conversations - doesn't make a difference), i don't get any controls or signs of OMEMO, although those controls and OMEMO status "enabled" are shown on the other end.

Some experimentation showed that the availability of OMEMO (buttons) depends on the XMPP server(s) in use or on their configuration:
With another contact or the same device/software contacting me over a different server i do get OMEMO buttons and the "OMEMO encryption enabled" status message.

Unlike issue 35 i don't see any connection to the presence of multiple device keys and restarting Gajim doesn't bring me those missing OMEMO buttons.
I disabled ESessions to make sure i'm not dealing with some interference between the two.

**Comment by cippaciong** [comment]
OMEMO needs [PEP](https://xmpp.org/extensions/xep-0163.html) to be enabled on the server to work.

**Comment by oodbur** [comment]
Nevertheless, the exact behaviour Gajim-OMEMO shows here seems unacceptable: In the described case when only one party is on a PEP-enabled server, we get "OMEMO encryption enabled" status on one end and messages from both parties are shown as encrypted while on the other end they are not.
And, shouldn't there be a meaningful warning message or something in place that tells the user why it fails and tell that case apart from missing client support?

**Comment by oodbur** [comment]
PEP is needed only for delivering the prekeys, right?
So OMEMO should only depend on PEP if the other party is not available for the initial key exchange. If I'm already getting answer messages from the other party there is no reason for OMEMO not to protect me. In our case, with both parties available at the same time, it could well do an old-fashioned synchronous key exchange, OTR-style. It could even partially cover the asynchronous case by sending a prekey in unencrypted messages until the other party reacts, in case i decide to communicate without encryption.
So maybe I should file a bug against the OMEMO spec?

**Comment by iNPUTmice** [comment]
This might be fixed in current HEAD. Please take a look and report back.

**Comment by lovetox** [comment]
@oodbur is this issue fixed for you with the current HEAD?

**Comment by lovetox** [comment]
I close this until there are more informations
