### ISSUE TITLE
messages silently swallowed although being shown as sent

### ISSUE THREAD

**Issue by oodbur** [kalkin/gajim-omemo#40]
OMEMO can only be activated sucessfully if the "Get device keys" button got pressed. Before that i can seemingly activate OMEMO and send messages (i.e. they show up in the conversation view and i got the "OMEMO encryption enabled" status message), but they silently get swallowed and never show up on the other end.
With the OMEMO checkbox unticked i can get successful delivery (of unencrypted messages).

**Comment by lovetox** [comment]
this should not be possible anymore with current HEAD
