### ISSUE TITLE
confusing user interface

### ISSUE THREAD

**Issue by oodbur** [kalkin/gajim-omemo#41]
Even after spending hours on the topic of OMEMO and such the (naming of the) buttons don't make any sense to me.
The buttons/interactive elements lack tooltips.

(Only) If i know what OMEMO is, the "OMEMO" checkbox is fairly intuitive.

The "Get device keys" button is permanently gone after i pressed it once. It leaves me with the question of what i have done and how i can repeat or reverse it.

There is no clear indication of which messages were encrypted and which ones were not.

With my contact using a XMPP server that is incompatible with this plugin here (see issue 39), the "OMEMO encryption enabled/disabled" status messages sometimes seem to give false negative indication of the OMEMO session status which is not consistent with the display on the other end where my seemingly unencrypted messages are shown as encrypted.

**Comment by oodbur** [comment]
With one contact i now even get two sets of OMEMO buttons.

**Comment by kalkin** [comment]
oodbur: I'm sorry for your experience. I am currently on the move. I will fix it as soon as I'm back at my workplace.

**Comment by kalkin** [comment]
Hi,

I'm sorry that my response took almost a month, real life and corrupt memory ... :smile: 

> The buttons/interactive elements lack tooltips.
> Not sure which tooltips you need, but patches are welcome.
> 
> (Only) If i know what OMEMO is, the "OMEMO" checkbox is fairly intuitive.

So what would you propose?

> The "Get device keys" button is permanently gone after i pressed it once. It leaves me with the question of what i have done and how i can repeat or reverse it.

You do not need to repeat or reverse it.

> There is no clear indication of which messages were encrypted and which ones were not.

Well it's only partly true. If you enable encryption, Gajim will print out _OMEMO encryption enabled_. If you receive an unencrypted message it will warn you, but still send the next message **encrypted**. I know the interface is not great, but that's what Gajim is currently capable of. Feel free to help out, the Gajim maintainers would appreciate any help.
