### ISSUE TITLE
UI must be moved into a menu or a panel

### ISSUE THREAD

**Issue by da2x** [kalkin/gajim-omemo#44]
There are too many devices on the list to fit on the screen. It takes up too much horizontal space. Should either be in a panel or a menu.

**Comment by iNPUTmice** [comment]
What devices are you talking about? Is the related to #45 I'm not seeing a list of devices anywhere.

**Comment by lovetox** [comment]
could you expand on your problem please, otherwise i will close this in a view days.

which device list are you talking about that doesnt fit the screen?
