### ISSUE TITLE
“Device” should use resource name instead

### ISSUE THREAD

**Issue by da2x** [kalkin/gajim-omemo#45]
“Device 1” and “Device 2“ etc. means nothing to users. Use their resource names instead as a human readable label. “Mobile”, “work”, etc. are much more relatable.

**Comment by SamWhited** [comment]
Resource names SHOULD NOT be human readable, they are on some clients, but won't be on others (and generally shouldn't be).

If anything, the client identity information from the caps should be used.

**Comment by da2x** [comment]
I assume “device” refers to to “resource”? Well, then the resource name really is the correct identifier/label to use. It will be unique per _device_.

**Comment by iNPUTmice** [comment]
Where are you seeing 'Device 1' and 'Device 2'?
Currenlty gajim-omemo doesn't allow you to trust devices (which is covered by a different issue)

**Comment by da2x** [comment]
Device 1 and 2 is disabled at the bottom of chat windows.

**Comment by da2x** [comment]
Shown here with just one device, but multiple devices will be added horizontally right next to this button labeled “Device 1”, “Device 2”, etc.
![screenshot from 2016-04-25 15-14-48](https://cloud.githubusercontent.com/assets/1102886/14784963/800bcbe0-0af8-11e6-8d46-c29527d3c501.png)

**Comment by iNPUTmice** [comment]
@Aeyoun ok thanks for clearing that up. That button means 'Get 1 device key' or 'Get 2 device keys' and not get keys for: device 1.

But that should be renamed nonetheless.
