### ISSUE TITLE
“Clear Devices” button is unambiguous

### ISSUE THREAD

**Issue by da2x** [kalkin/gajim-omemo#46]
What devices? What happens when I click it? Even after clicking it, nothing seems to happen.

Should give feedback when clicked, and include a list of devices in a tooltip or something.

The button is also really prominently placed in the UI. Should be moved to a tab in the Contact information dialog where users can revoke individual devices.

**Comment by iNPUTmice** [comment]
Actually this should be placed in the Account menu under actions, advanced, $account, clear devices. But gajim doesn't provide a hook for this yet. We should ask the gajim developers to provide one.

**Comment by lovetox** [comment]
this button has now been placed in the config menu of the OMEMO plugin, with a device list.
