### ISSUE TITLE
Message sent unencrypted even though OMEMO is checked

### ISSUE THREAD

**Issue by RalfJung** [kalkin/gajim-omemo#49]
I have a peer where messages are sent unencrypted even though I have checked the "OMEMO" checkbox. Conversations shows no padlock on these messages.

There is no log output about this. I guess I need to somehow enable more debug logs?

This is with ff6f7d83055999813c680a9025e2392eface1efd of the plugin.

**Comment by iNPUTmice** [comment]
This was a regression introduced with d970936e15c13e4738de37b0d2a60193ed828041.
I reverted that commit.
