### ISSUE TITLE
Cannot install OMEMO in Gajim-nightly

### ISSUE THREAD

**Issue by asterismo** [kalkin/gajim-omemo#52]
Hi guys I'm sorry to bring this up again, but i cannot install OMEMO plugin via the plugin manager on gajim-nightly. I added the gajim unstable repo in my Debian 8 jessie, installed via sudo pip2 the axolotl, and messages show a sucsessfull installation, and OMEMO shows up as installed when enabling it from the plugin, but i got the warning in the textbox about the python-axolotl. The plugin does not check and hitting configure returns an empty box doing nothing, so it is not working. Any ideas?

sudo pip2 install python-axolotl --upgrade
[sudo] password for santiago: 
Requirement already up-to-date: python-axolotl in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: pycrypto in /usr/lib/python2.7/dist-packages (from python-axolotl)
Requirement already up-to-date: python-axolotl-curve25519 in /usr/local/lib/python2.7/dist-packages (from python-axolotl)
Requirement already up-to-date: protobuf>=3.0.0.b2 in /usr/local/lib/python2.7/dist-packages (from python-axolotl)
Cleaning up...

I also tried to remove all gajim folder in .config and .local and purging/reinstalling it, so...

cheers!

**Comment by ilsi** [comment]
Hi,

I also had problems with OMEMO after upgrade protobuf to version 3.0.0b2. Downgrading solved the issue for me. You could try to downgrade this package:
`sudo pip install 'protobuf>=2.6,<3.0.0'`

**Comment by kalkin** [comment]
@asterismo Was the issue solved for you?

**Comment by kalkin** [comment]
OMEMO should work with `protobuff==3.0.0b2`. It has issues with the version `python-protobuf 3.0.0b2.post2`. Please see #55. I will close this issue for now as a duplicate,but if you think you have a different error, feel free to comment and I will reopen this issue
