### ISSUE TITLE
You need to install python-axolotl via pip to run this plugin. 

### ISSUE THREAD

**Issue by qamble** [kalkin/gajim-omemo#54]
What is this or how do I do this?  The plugin manager finally successfully downloaded OMEMO after I created a ticket.  Such is my life.

windows 8.1 64bit

**Comment by kalkin** [comment]
> What is this or how do I do this?

Pip the PyPA recommended tool for installing Python packages.

> The plugin manager finally successfully downloaded OMEMO after I created a ticket

Always be patient young padawan :smile: 

> windows 8.1 64bit 

I only use free software, I can't help you ☹. If you are really interested in getting to run it on windows see #12 and please report your progress there. Patches are welcome.
