### ISSUE TITLE
Ubuntu Gajim: not detecting python-axolotl

### ISSUE THREAD

**Issue by catvec** [kalkin/gajim-omemo#57]
**OS**: Ubuntu 16.04 xenial  
**Python**: Python 2.7.11+  
**PIP**: pip 8.1.1 from /usr/lib/python2.7/dist-packages (python 2.7)  
**Gajim**: 0.16.5  

```
$ sudo -H pip list | grep python-axolotl
python-axolotl (0.1.35)
python-axolotl-curve25519 (0.1)
$ python -c "import axolotl"
```

_If you would like me to run any more commands to get information about my system I would be glad to provide their outputs._

---

After installing the `gajim-omemo` plugin via the Gajim UI I saw the warning and installed `python-axolotl` via PIP and rebooted.  

However when I reopened Gajim and went to enable the plugin the warning ("Warning: Please install python-axolotl.") was still there. In the system information block above, you will see how I verified that `python-axolotl` was installed via PIP and that I could import the `axolotl` module in the Python REPL.

**Comment by iNPUTmice** [comment]
I think this could be duplicate. Please read through previous issues and double check

**Comment by lovetox** [comment]
https://github.com/omemo/gajim-omemo/issues/55

check your protobuf version.
the message itself "please install axolotl" could mean other dependencys are missing.

**Comment by lovetox** [comment]
@Noah-Huppert so is this issue still present for you? or else i will close this

**Comment by catvec** [comment]
Installing the correct protobuf version fixed this issue. However I think showing an error message warning the user to install a python dependency that is already installed is not the right course of action when the root cause of an the issue is something else.

**Comment by lovetox** [comment]
I have it on my list, the error message will print whats really missing in the future.
thanks
