### ISSUE TITLE
Pressing "Get Device Keys" should show some immediate reaction

### ISSUE THREAD

**Issue by RalfJung** [kalkin/gajim-omemo#60]
When I press "Get Device Keys", it sometimes takes up to 30 seconds until the button disappears. That makes it look like pressing the button did not do anything. There should always be _some_ immediate reaction to signal to the user: Yep, I got you, working on it.
For example, the button could turn into some text, "Fetching Device Keys... <Cancel>" (or mayb cancelling makes no sense).

**Comment by lovetox** [comment]
why not deleting this button and get the keys automatically?
is there a reason to _not_ get the device keys ever?
@kalkin

**Comment by RalfJung** [comment]
Well, certainly we don't want to trust any random device key appearing for a contact.

**Comment by lovetox** [comment]
to decide if you trust a key or not, you first have to get it, or not?
of course the key should be shown and a decision should be made to accept or not.
but i think this is covered by another issue.

**Comment by RalfJung** [comment]
Well, so far the plugin employs a TOFU strategy. Until that is changed (which that other, unnamed issue is about, if I understand you correctly), doing automatic acceptance of keys instead would be a horrible security mess.

**Comment by lovetox** [comment]
https://github.com/omemo/gajim-omemo/pull/61/commits/556fee90327e9b07b5de7cd6c7fff2dbbf07e762

**Comment by lovetox** [comment]
@RalfJung 
please use the new HEAD, the button is gone, fingerprint UI has been added.
