### ISSUE TITLE
renamed account breaks omemo

### ISSUE THREAD

**Issue by grinapo** [kalkin/gajim-omemo#65]
Steps to reproduce:
- create account
- get device keys, connect, whatever you please
- disconnect account
- rename account
- connect
- fail
  
  File "/home/anybody/.local/share/gajim/plugins/omemo/**init**.py", line 85, in get_omemo_state
    conn = sqlite3.connect(db_path, check_same_thread=False)
  OperationalError: unable to open database file

**Comment by lovetox** [comment]
thanks for finding this, i will look into this

**Comment by lovetox** [comment]
a workaround is to rename the db file, like the new account.
and start gajim new.

but nevertheless this is not intended.

i cant really reproduce this error msg though, all i get is a new omemo db with the new account

@kalkin 
would it be better to bind the db name to our own jid?
changing the sign in jid in an account would trigger a new db created, and i think people would find this logical.

though when someone adds 2 accounts with the same JID, bad stuff will happen. but who does that.

**Comment by kalkin** [comment]
@lovetox Not sure. I think there was a reason we used the account name, but I can't remember it

**Comment by lovetox** [comment]
in 0.9.5 the DB is named after JID, so this feature of gajim should work now without breaking something.

after renaming an account, a restart should happen.
