### ISSUE TITLE
Images and files sent with OMEMO enabled are unretrievable

### ISSUE THREAD

**Issue by Semperverus** [kalkin/gajim-omemo#69]
When sending files or images to a Gajim user using OMEMO, those files remain encrypted. The plugin needs to decrypt before the file is stored.

Additionally, this same issue crops up with httpupload, especially with Conversations. It appears as though some sort of hash is put onto the end of the filename after a # symbol.

While multi-endpoint encryption has been very useful, this has been a major inhibitor. Conversations is able OMEMO file transfers seamlessly, so that should be the target here as it has been shown to be possible.

**Comment by cippaciong** [comment]
Hello, most of these problems have already been reported in #19. In that issue you will find a broader discussion about who is responsible to encrypt/decrypt images as well as a couple of immediate workarounds to open encrypted images even in gajim using an external component.

**Comment by lovetox** [comment]
thanks this is reported already
In the next version of Gajim there will be more crypto librarys and there will be plugins who can decrypt.

meanwhile you can use the imagedownloader from inputmice. see https://github.com/omemo/gajim-omemo/issues/19

**Comment by Semperverus** [comment]
I see. I skipped over that one as it sounded to be the exact opposite of my problem from its title (that nothing was being encrypted, where for me everything is being encrypted)
