### ISSUE TITLE
own OMEMO key is published very often

### ISSUE THREAD

**Issue by silberzwiebel** [kalkin/gajim-omemo#70]
While trying to track down bug #51 I've observed that the plugin publishes it's own key very often. It appears many times in the device list and if I clear the list it appears back. The log is full of [messages lke this](https://gist.github.com/silberzwiebel/409982aeb1eaed21613ad73ce5611554)

**Comment by lovetox** [comment]
thats not a key
thats the device ID

every device has an ID, we publish that ID so other people can get the ID, with this ID they query our server with the encryption keys.

which of your devices is 321776365
something very wrong is going on here, a device ID should only be once in the Publish.

**Comment by lovetox** [comment]
if this ID is infact the OMEMO Plugin, there could be a bug. we remove duplicates out of the publish what obviously does not work here

if you clear device list, how long does it need to get to such a long device list

**Comment by lovetox** [comment]
i found the bug, i will fix that now, thanks.

**Comment by lovetox** [comment]
though i wonder could you look at your sessions table, in the omemo sqlite DB
are there many entrys for the same device ID?

**Comment by lovetox** [comment]
you can try my bugfix branch, and see if the problem still exists

https://github.com/lovetox/gajim-omemo/commits/bugfix

**Comment by lovetox** [comment]
even though there was a bug, it can only show it self under very specific circumstances, i believe in your DB could be something wrong.

if you dont care that your contacts get a new fingerprint, i would try to delete db and start new

**Comment by lovetox** [comment]
so did your problem go away?
@silberzwiebel

**Comment by silberzwiebel** [comment]
Sorry for the late reply.
I tried to reproduce the error with the not-bugfixed-plugin some days
ago but couldn't managed to do so. I wanted to do this to be able to see
whether yoouir bugfix truly fixed the bug, i.e., if I would do the same
steps then the bug would not apppear.

I did not have any related problems with your bugfix-repo until now, though.

What files would I need to delete if I want to clean my local OMEMO
database? Maybe this then also resolves the bug #51 for me (which is
also hard to re-produce for me...)

**Comment by lovetox** [comment]
just delete the file omemo_yourserver.db then restart.

but beware you get a new key, and your contacts have to trust your new fingerprint again.

i wouldnt do this though if your problems are now gone, i think maybe that there were multiple problems at once that makes it hard to focus on the thing thats not working correctly.

it was definitely not optimal the way it was with the key publishing, but now it should work even when your db is not in an optimal state.

**Comment by lovetox** [comment]
this should be fixed with version 0.7
