### ISSUE TITLE
Widget not deleted 

### ISSUE THREAD

**Issue by threonorm** [kalkin/gajim-omemo#78]
When the plugin is deactivated in gajim, the button in the UI is not removed. 

Then when the plugin is reactivated, a new button is created and there are 2 buttons.

The problem may be in ui.py, the `__init__` for the class UI create the widget with

`_add_widget(self.omemobutton, self.chat_control)
`
and it seems that nobody never removes this widget.

**Comment by lovetox** [comment]
ha, you are right, good catch, never had the idea to deactivate the plugin

**Comment by lovetox** [comment]
should be fixed with newest HEAD, you can test if you want.

thanks for reporting
