### ISSUE TITLE
Can't see my own encrypted messages from gajim no longer on Conversations (Android)

### ISSUE THREAD

**Issue by amenk** [kalkin/gajim-omemo#81]
1. Upgraded to Plugin 0.7.0, latest Gajim Nightly
2. Write a message in chat on gajim with OMEMO
3. can't see it on Conversations on Android

Unencrypted I see the message

Probably Gajim is missing my mobil's key?
But in Gajim I see only the keys of my chat partner, not of my mobile.

**Comment by fuesschen** [comment]
Goto the plugin settings and verify your own fingerprint under "Known Fingerprints"

**Comment by amenk** [comment]
I was able to fix it via the plugin settings -> known devices -> refresh -> the key of my mobile appeared under known keys -> clicked verified

Thanks so far... 

But this whole key management is a mess :-( Too complicated. Is there a specific reason why there can not be a popup just prompting me to accept a new key or is it just not developed yet?

**Comment by amenk** [comment]
Just flattred the repo ... :-)

**Comment by lovetox** [comment]
hi, on first use the plugin works not really flawless, after installing its always better to start gajim new and sign into your account to retrieve all keys.

the problems on first use are known and will be adressed in future versions.

key management could probably be easier, i probably make some room for a "own keys" table.

**Comment by lovetox** [comment]
hi in the last commit i added a TAB so you can see your own Device Fingerprints in the Fingerprint Dialog that opens from the Chat Window.

No need to search for it in the Config Dialog anymore.
