### ISSUE TITLE
Add possibility to delete Fingerprints

### ISSUE THREAD

**Issue by tanty** [kalkin/gajim-omemo#91]
Right now, the only option is to verify.

It would be good to add the possibility to remove and revoke

**Comment by lovetox** [comment]
@tanty you can revoke, just click verify and then on the dialog NO

**Comment by tanty** [comment]
@lovetox Wow, I DID miss that!

Then, I think the text in the button is a bit ambiguous. "Verify fingerprint" sounds to me like it can only be done in a "positive" fashion. I was not even expecting a dialog.

Also, it would be nice still if you could delete the key, but this is really a wish.

**Comment by lovetox** [comment]
maybe "verify/revoke" would be better

what do you expect from a deletion?
what if it is the only fingerprint of your contact, should it come up again as undecided the next start?
or
does deletion mean "i want to see that fingerprint never again?"

**Comment by tanty** [comment]
"verify/revoke" sounds good to me

I would expect the first:
"It should come again as undecided the next start, if the contact keeps using that fingerprint"

**Comment by lovetox** [comment]
is in 0.9.5 possible now.
